In [3]:
%logstop
%logstart -rtq ~/.logs/dw.py append
import seaborn as sns
sns.set()

In [4]:
from static_grader import grader

# DW Miniproject
## Introduction

The objective of this miniproject is to exercise your ability to wrangle tabular data set and aggregate large data sets into meaningful summary statistics. We'll work with the same medical data used in the `pw` miniproject but leverage the power of Pandas to more efficiently represent and act on our data.

## Downloading the data

We first need to download the data we'll be using from Amazon S3:

In [5]:
!mkdir dw-data
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/201701scripts_sample.csv.gz -nc -P ./dw-data/
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/201606scripts_sample.csv.gz -nc -P ./dw-data/
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/practices.csv.gz -nc -P ./dw-data/
!wget http://dataincubator-wqu.s3.amazonaws.com/dwdata/chem.csv.gz -nc -P ./dw-data/

mkdir: cannot create directory ‘dw-data’: File exists
File ‘./dw-data/201701scripts_sample.csv.gz’ already there; not retrieving.

File ‘./dw-data/201606scripts_sample.csv.gz’ already there; not retrieving.

File ‘./dw-data/practices.csv.gz’ already there; not retrieving.

File ‘./dw-data/chem.csv.gz’ already there; not retrieving.

## Loading the data

Similar to the `pw` miniproject, the first step is to read in the data. The data files are stored as compressed CSV files. You can load the data into a pandas `DataFrame` by making use of the `pd.read_csv` function to parse the data into a `DataFrame`. You may want to check the pandas documentation for parsing [CSV](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) files for reference.

For a description of the data set please, refer to the [`pw` miniproject](./pw.ipynb). **Note that all questions make use of the 2017 data only, except for Question 5 which makes use of both the 2017 and 2016 data.**

In [6]:
import pandas as pd
import numpy as np

In [7]:
# load the 2017 data
scripts = pd.read_csv('dw-data/201701scripts_sample.csv.gz')
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [8]:
col_names=[ 'code', 'name', 'addr_1', 'addr_2', 'borough', 'village', 'post_code']
practices = pd.read_csv('dw-data/practices.csv.gz',names=col_names , header=None)
practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,NaN,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [9]:
chem = pd.read_csv('dw-data/chem.csv.gz')
chem.head()

    CHEM SUB                                NAME
0  0101010A0                     Alexitol Sodium
1  0101010B0                          Almasilate
2  0101010C0                 Aluminium Hydroxide
3  0101010D0  Aluminium Hydroxide With Magnesium
4  0101010E0                        Hydrotalcite

Now that we've loaded in the data, let's first replicate our results from the `pw` miniproject. Note that we are now working with a larger data set so the answers will be different than in the `pw` miniproject even if the analysis is the same.

## Question 1: summary_statistics

In the `pw` miniproject we first calculated the total, mean, standard deviation, and quartile statistics of the `'items'`, `'quantity'`', `'nic'`, and `'act_cost'` fields. To do this we had to write some functions to calculate the statistics and apply the functions to our data structure. The DataFrame has a `describe` method that will calculate most (not all) of these things for us.

Submit the summary statistics to the grader as a list of tuples: `[('act_cost', (total, mean, std, q25, median, q75)), ...]`

In [10]:
len(scripts)

973193

In [11]:
scripts.describe()

               items            nic       act_cost       quantity
count  973193.000000  973193.000000  973193.000000  973193.000000
mean        9.133136      73.058915      67.986613     741.329835
std        29.204198     188.070257     174.401703    3665.426958
min         1.000000       0.000000       0.040000       0.000000
25%         1.000000       7.800000       7.330000      28.000000
50%         2.000000      22.640000      21.220000     100.000000
75%         6.000000      65.000000      60.670000     350.000000
max      2384.000000   16320.000000   15108.320000  577720.000000

In [12]:
scripts.describe().loc[['mean','std']]

          items         nic    act_cost     quantity
mean   9.133136   73.058915   67.986613   741.329835
std   29.204198  188.070257  174.401703  3665.426958

In [13]:
fields=['items','nic','act_cost','quantity']
scripts[fields].describe().loc[['mean','std','25%','50%','75%']]

          items         nic    act_cost     quantity
mean   9.133136   73.058915   67.986613   741.329835
std   29.204198  188.070257  174.401703  3665.426958
25%    1.000000    7.800000    7.330000    28.000000
50%    2.000000   22.640000   21.220000   100.000000
75%    6.000000   65.000000   60.670000   350.000000

In [14]:
scripts[fields].sum()

items       8.888304e+06
nic         7.110042e+07
act_cost    6.616410e+07
quantity    7.214570e+08
dtype: float64

In [15]:
scripts[fields].describe().loc[['mean','std','25%','50%','75%']].T
#transposed

                mean          std    25%     50%     75%
items       9.133136    29.204198   1.00    2.00    6.00
nic        73.058915   188.070257   7.80   22.64   65.00
act_cost   67.986613   174.401703   7.33   21.22   60.67
quantity  741.329835  3665.426958  28.00  100.00  350.00

In [16]:
# create a new dataframe with total, mean, std,25%,50%,75% quartile
summary = pd.concat([scripts[fields].sum(),scripts[fields].describe().loc[['mean','std','25%','50%','75%']].T],axis=1)

In [17]:
summary

                     0        mean          std    25%     50%     75%
items     8.888304e+06    9.133136    29.204198   1.00    2.00    6.00
nic       7.110042e+07   73.058915   188.070257   7.80   22.64   65.00
act_cost  6.616410e+07   67.986613   174.401703   7.33   21.22   60.67
quantity  7.214570e+08  741.329835  3665.426958  28.00  100.00  350.00

In [18]:
summary.columns=['total','mean','std','25%','50%','75%']

In [19]:
summary

                 total        mean          std    25%     50%     75%
items     8.888304e+06    9.133136    29.204198   1.00    2.00    6.00
nic       7.110042e+07   73.058915   188.070257   7.80   22.64   65.00
act_cost  6.616410e+07   67.986613   174.401703   7.33   21.22   60.67
quantity  7.214570e+08  741.329835  3665.426958  28.00  100.00  350.00

In [20]:
 for i in summary.itertuples():
        print(i)

Pandas(Index='items', total=8888304.0, mean=9.133135976111625, std=29.204198282803603, _4=1.0, _5=2.0, _6=6.0)
Pandas(Index='nic', total=71100424.84000002, mean=73.05891517920908, std=188.070256906825, _4=7.8, _5=22.64, _6=65.0)
Pandas(Index='act_cost', total=66164096.11999999, mean=67.98661326170655, std=174.40170332301963, _4=7.33, _5=21.22, _6=60.67)
Pandas(Index='quantity', total=721457006.0, mean=741.3298348837282, std=3665.426958467915, _4=28.0, _5=100.0, _6=350.0)

In [21]:
for i in summary.itertuples():
        print((i[0],i[1:]))

('items', (8888304.0, 9.133135976111625, 29.204198282803603, 1.0, 2.0, 6.0))
('nic', (71100424.84000002, 73.05891517920908, 188.070256906825, 7.8, 22.64, 65.0))
('act_cost', (66164096.11999999, 67.98661326170655, 174.40170332301963, 7.33, 21.22, 60.67))
('quantity', (721457006.0, 741.3298348837282, 3665.426958467915, 28.0, 100.0, 350.0))

In [22]:
[(i[0],i[1:]) for i in summary.itertuples()]

[('items', (8888304.0, 9.133135976111625, 29.204198282803603, 1.0, 2.0, 6.0)),
 ('nic',
  (71100424.84000002, 73.05891517920908, 188.070256906825, 7.8, 22.64, 65.0)),
 ('act_cost',
  (66164096.11999999,
   67.98661326170655,
   174.40170332301963,
   7.33,
   21.22,
   60.67)),
 ('quantity',
  (721457006.0, 741.3298348837282, 3665.426958467915, 28.0, 100.0, 350.0))]

In [23]:
summary_stats = [(i[0],i[1:]) for i in summary.itertuples()]

In [24]:
#summary_stats = [('items', (0,) * 6), ('quantity', (0,) * 6), ('nic', (0,) * 6), ('act_cost', (0,) * 6)]

In [25]:
grader.score.dw__summary_statistics(summary_stats)

==================
Your score: 1.000
==================

## Question 2: most_common_item

We can also easily compute summary statistics on groups within the data. In the `pw` miniproject we had to explicitly construct the groups based on the values of a particular field. Pandas will handle that for us via the `groupby` method. This process is [detailed in the Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/groupby.html).

Use `groupby` to calculate the total number of items dispensed for each `'bnf_name'`. Find the item with the highest total and return the result as `[(bnf_name, total)]`.

In [26]:
group_bnf = scripts.groupby('bnf_name')

In [27]:
group_bnf.groups
#it is a dictionary with key=bnf_name 
#and value =list of rowindexes having that bnf_name.

{'365 Film 10cm x 12cm VP Adh Film Dress': [824938], '365 Non Adherent 10cm x 10cm Pfa Plas Fa': [569412, 876439, 932168], '365 Non Adherent 10cm x 20cm Pfa Plas Fa': [638246], '365 Non Woven Island 8cm x 10cm Adh Dres': [82909], '365 Transpt Island 5cm x 7.2cm VP Adh Fi': [475466, 481797], '365 Transpt Island 8.5cm x 15.5cm VP Adh': [481798], '3M Micropore Silicone 2.5cm x 5m Surg Ad': [95527, 230685, 286346, 493077, 512128, 618948, 687437, 889945, 937581, 973024], '3M Micropore Silicone 5cm x 5m Surg Adh': [417386, 477179, 502271, 553732, 595033, 620579, 957276], '3m Health Care_Cavilon Durable Barrier C': [1489, 1491, 3296, 5348, 5350, 8491, 8493, 9719, 10362, 13448, 15162, 15164, 17006, 17007, 18941, 18945, 20926, 20927, 22024, 23744, 25443, 26710, 28398, 28623, 28625, 30275, 30278, 33296, 36343, 36345, 40524, 41673, 44324, 46556, 49594, 52782, 52783, 52786, 54274, 55921, 58527, 60478, 60481, 61412, 63225, 63227, 66935, 68643, 68645, 70845, 72330, 73212, 76465, 77799, 77801, 79499, 81413, 83107, 83109, 84379, 84380, 86231, 88749, 88750, 88752, 91197, 92767, 94349, 95622, 95623, 96683, 98001, 98003, 99093, 100283, 103456, 105173, 106488, 108700, 108701, 111389, 111390, 115483, 117549, 119102, 120381, 120383, 121659, 121660, 122822, 124038, 125595, 127375, 127377, 128691, 129966, 132504, 133540, 134718, 135969, ...], '3m Health Care_Cavilon No Sting 1ml Barr': [5349, 9720, 10363, 12129, 13449, 15163, 17008, 18942, 20928, 22025, 23348, 23745, 25444, 26711, 28396, 28624, 30276, 33297, 36344, 37771, 41674, 44325, 52784, 54275, 60479, 61410, 61786, 72329, 83108, 101442, 103457, 132505, 140311, 142037, 144087, 149998, 153789, 155025, 156953, 174683, 175596, 180096, 184321, 186969, 193880, 202887, 205149, 207812, 210862, 212347, 223535, 232545, 234566, 241611, 245298, 246909, 250429, 252312, 253537, 255176, 256897, 260538, 262327, 264397, 268195, 281778, 286521, 288458, 298998, 300982, 304304, 309919, 316615, 318259, 320890, 322526, 326738, 328270, 335174, 336023, 340848, 346940, 349767, 354142, 356315, 357205, 358783, 360452, 363264, 364645, 366466, 367367, 373565, 375481, 377016, 381603, 389786, 392491, 394386, 395644, ...], '3m Health Care_Cavilon No Sting 3ml Barr': [1490, 18943, 44326, 52785, 58528, 74666, 87291, 101443, 115482, 134719, 137431, 138326, 140312, 144088, 146651, 147691, 155026, 157839, 174684, 195890, 202888, 206258, 245299, 250430, 256898, 269558, 300983, 304305, 309920, 312463, 320891, 322527, 324290, 326739, 329553, 331618, 333155, 334023, 364646, 377017, 401845, 410270, 416032, 421832, 435967, 436268, 441079, 469202, 480218, 493216, 499658, 510522, 540861, 550370, 553923, 575127, 583491, 595319, 595725, 597439, 602239, 606067, 606487, 606800, 610076, 615173, 622759, 630107, 631755, 640228, 646880, 661049, 684115, 689196, 706062, 709582, 722880, 757270, 758650, 762994, 788467, 794390, 849787, 851418, 853247, 854796, 857801, 860543, 861979, 865523, 890307, 899053, 932364, 942544], '3m Health Care_Cavilon No Sting Barrier': [3297, 5347, 8492, 9721, 10364, 13447, 13450, 17009, 18944, 23347, 23349, 28397, 30274, 30277, 37772, 40525, 42926, 44323, 44327, 46555, 46557, 49595, 55920, 57146, 60477, 60480, 61411, 63224, 63226, 64798, 66934, 66936, 68644, 70843, 70844, 76466, 77800, 79500, 81414, 88748, 88751, 96682, 98002, 99092, 101444, 103458, 105172, 117550, 120382, 122823, 127376, 127515, 132506, 137432, 140313, 142035, 144089, 145537, 173316, 178353, 184322, 185510, 186970, 188677, 192375, 192376, 195891, 197505, 199110, 200626, 205147, 216145, 217732, 223536, 225532, 232543, 234567, 237653, 239873, 243553, 245300, 249066, 252310, 252313, 256895, 258729, 260539, 264398, 266001, 268193, 268196, 269557, 280001, 281779, 284830, 286522, 288456, 288459, 290436, 293910, ...], '4Head_Top Headache Relief Stick': [426322, 472869, 837794, 906276], 'A & P_Infants Pdrs': [219595, 524344, 536169, 829757, 925996], 'A.S Saliva Orthana Spy 50ml (App)': [16911, 18801, 23693, 34380, 36223, 37696, 45219, 49473, 55827, 57088, 135937, 138302, 140253, 144005, 149074, 151797, 157811, 166258, 190011, 199037, 205084, 213300, 230758, 239719, 241497, 243430, 245202, 252187, 264288, 265916, 268054, 278153, 279908, 286417, 288297, 290303, 314488, 320806, 342301, 345074, 349671, 354071, 355086, 356259, 363180, 373503, 375348, 378302, 379629, 381495, 391164, 401758, 415872, 419176, 421762, 423625, 440984, 442748, 459378, 466085, 470268, 472037, 473976, 487309, 505581, 512204, 517054, 538188, 540754, 554932, 556516, 563599, 568563, 573891, 579550, 599773, 621250, 626489, 630050, 649343, 660908, 667011, 684005, 685677, 687511, 689088, 701114, 707832, 735375, 740793, 744293, 745947, 749516, 757189, 772320, 807568, 814840, 816695, 823872, 833227, ...], 'A.S Saliva Orthana Spy Refill 500ml (App': [36224, 293806, 316567, 423626, 925325, 943991], 'A.T. 10_Soln 0.25mg/1ml': [631275], 'A2A Spacer': [88619, 127274, 133463, 239632, 260387, 272065, 346756, 427043, 428945, 487232, 522273, 657947, 660825, 662024, 663608, 707763, 833153, 851265, 871681, 874636, 879990, 910747, 916306], 'A2A Spacer + Sml/Med Mask': [6716, 50842, 52589, 81224, 131175, 132411, 137364, 143950, 161752, 181496, 188524, 190833, 203904, 232410, 239633, 265868, 272066, 278116, 290232, 300784, 316539, 342247, 346757, 352624, 368490, 381411, 500835, 512137, 513820, 528981, 532395, 535456, 561338, 569437, 590740, 628358, 657948, 660826, 662025, 663609, 668236, 707764, 742625, 744240, 747490, 764254, 776710, 805926, 808845, 819096, 833154, 834504, 836657, 844261, 871682, 881433, 914260, 920697, 936216, 940028, 942401, 945511], 'AAA_Sore Throat A/Spy 7.5g': [202636, 274612, 352524, 784522], 'ACC-600_Tab Eff': [642193], 'AMI_Corsinel Suportx Ab Belt High Wte Ex': [241582], 'AMI_Corsinel Suportx Ab Belt Low Wte Sml': [591906], 'AMI_Corsinel Suportx Ab Tube Wte ExLge (': [522394], 'AMI_Corsinel Suportx Ab Tube Wte Lge (94': [281746, 345155, 346904, 507219], 'AMI_Corsinel Suportx Ab Tube Wte Med (86': [54250, 322504, 579655, 606345], 'AMI_Corsinel Suportx Ab Tube Wte Sml (78': [309860, 594989], 'AMI_Corsinel Suportx Easy Panel Belt Wte': [252276], 'AMI_Corsinel Suportx M/M Fle': [101297, 345154, 577644], 'AMI_Corsinel Suportx M/M Male': [671527, 934867], 'AMI_Suportx Hernia Support Girdles Fle H': [18902, 722821, 742781, 916491, 955558], 'AMI_Suportx Hernia Support Girdles Fle L': [52740, 183408, 188657, 197488, 213335, 241581, 309857, 322502, 345153, 346903, 366436, 461248, 605851, 606340, 609975, 722822, 726087, 752605, 851399], 'AMI_Suportx Hernia Support Girdles Male': [40507, 210840, 309858, 520772, 667098, 699687], 'AMI_Suportx Ostomy & A/Support Ladies Br': [1462, 50942, 50943, 105146, 105147, 526003, 526004, 606341, 606342, 606343, 606694], 'AMI_Suportx Ostomy Support Mens Shorts B': [387825, 606335, 606688], 'AMI_Suportx Ostomy Support Mens Shorts D': [387826, 973165], 'AMI_Suportx Ostomy Support Mens Shorts W': [609972], 'AMI_Suportx Ostomy Support Mens Trunks B': [47701, 103430, 115456, 441050, 606689, 651113, 821024, 846407], 'AMI_Suportx Ostomy Support Mens Trunks D': [591905, 606690, 609973, 973166], 'AMI_Suportx Ostomy/Hernia E/Peel Supp/Be': [316603, 961104], 'AMI_Suportx Ostomy/Hernia Easy Peel Supp': [149991, 210841, 225530, 309859, 320867, 333129, 375438, 387827, 389735, 391219, 419237, 594988, 595116, 595117, 595573, 605852, 606344, 606695, 609976, 648315, 687595, 693540, 722823, 724301, 737409, 746008, 859214, 861959, 899031, 914425, 914426, 951969, 955559], 'AMI_Suportx Ostomy/Hernia Support Belt 1': [228918, 322503], 'APO-go PEN_Inj 10mg/ml 3ml Pf Pen': [17834, 24508, 222851, 229813, 280769, 362349, 393298, 405407, 471117, 501541, 511265, 539822, 551116, 613696, 696867, 703670, 725101, 814158, 903633, 927015, 935520], 'APO-go PFS_Inf 5mg/ml 10ml Pfs': [12747, 17835, 35240, 73886, 113354, 301802, 308246, 362350, 426430, 471118, 504779, 551117, 570872, 592589], 'AS Saliva Orthana_Loz': [72012, 104815, 133342, 138188, 235573, 239373, 288012, 289997, 305300, 309233, 425318, 572407, 666655, 723984, 807295, 957029], 'Abasaglar KwikPen_100u/ml 3ml Pf Pen': [16127, 22722, 24625, 35380, 82301, 102694, 104362, 112726, 114456, 116022, 128328, 133040, 174089, 179347, 180911, 184982, 187876, 190559, 205736, 207116, 208574, 210096, 213957, 218313, 220986, 222961, 225969, 228177, 244487, 251439, 284150, 287481, 289465, 293101, 315278, 393443, 465151, 479335, 484930, 486369, 495221, 496490, 500081, 511415, 518147, 521642, 525192, 527021, 532036, 534000, 544356, 545516, 547935, 553056, 554485, 559031, 560150, 561014, 563183, 566150, 567083, 575600, 576454, 618232, 630966, 632451, 661618, 662718, 681691, 684952, 689890, 691092, 698851, 700507, 702085, 703821, 731110, 760687, 772923, 774437, 776391, 779037, 780305, 780939, 785435, 786621, 787867, 788972, 789975, 791035, 792101, 793162, 794993, 796589, 798091, 798949, 800129, 801983, 847271, 848844, ...], 'Abasaglar_100u/ml 3ml Cart': [19971, 21536, 24624, 27601, 102693, 114455, 291369, 428167, 486368, 551242, 561013, 569944, 573352, 575599, 585990, 691091, 697009, 778131, 847270, 848843, 852377, 856909, 863187, 874093, 954713], 'Abidec_Dps': [1048, 6402, 14647, 20329, 21726, 29819, 35723, 55412, 58123, 62767, 64347, 66262, 68092, 70137, 71875, 72970, 74266, 78952, 80809, 82578, 83997, 85624, 86997, 88323, 89512, 92269, 95228, 96390, 97601, 98796, 99912, 100667, 102971, 104664, 106152, 107319, 108415, 109429, 110129, 111109, 111969, 112915, 114834, 116195, 117302, 118700, 120061, 121334, 122527, 123719, 125210, 126901, 128482, 129647, 130209, 130959, 132146, 133239, 134348, 135624, 139718, 141573, 143499, 145090, 146369, 147397, 148706, 149767, 151589, 152265, 153389, 154682, 155598, 156661, 157590, 159247, 160193, 161451, 163151, 164547, 167301, 168322, 169317, 170579, 171715, 172962, 174321, 175375, 176493, 177933, 179655, 181196, 185189, 186539, 195262, 198639, 201342, 204796, 207384, 208814, ...], 'Abidec_Multivit Syr With Omega 3': [854328], 'Abilar Resin Salve 20g Tube Wound Dress': [232378, 260362, 614851], 'Abilify Maintena_Inj 400mg Vl + Dil P/R': [487914], 'Abilify_Oral Soln 1mg/ml': [247501, 526577, 757658, 844953], 'Abilify_Orodisper Tab 10mg': [880588], 'Abilify_Orodisper Tab 15mg': [536391], 'Abilify_Tab 10mg': [67396, 271201, 524773, 542499, 544159, 591141, 592366], 'Abilify_Tab 15mg': [499880], 'Abilify_Tab 30mg': [54725, 587451], 'Abilify_Tab 5mg': [292729, 384358, 509552, 524774, 632134, 652883, 692632, 810136, 822094, 922829, 959533], 'Able Spacer': [26, 1359, 3110, 5149, 6717, 11975, 13335, 14976, 18722, 20724, 25287, 28240, 33186, 40430, 47635, 54166, 55765, 63080, 64669, 68500, 72229, 81225, 95532, 103314, 109607, 127275, 132412, 140198, 149957, 161753, 168451, 179985, 188525, 195707, 197389, 201592, 241421, 243356, 245138, 248837, 253439, 258562, 260388, 262180, 264211, 278117, 281586, 283182, 284718, 286352, 288227, 290233, 293750, 295331, 298876, 300785, 302647, 304175, 306947, 309616, 310888, 312344, 313345, 315232, 318132, 322378, 328147, 340700, 345006, 354025, 358619, 360285, 361523, 363129, 366282, 368491, 375276, 378252, 379569, 381412, 401700, 408501, 410110, 411010, 423538, 433850, 436214, 439416, 442685, 466001, 477185, 487233, 488892, 490265, 495809, 496935, 503905, 505520, 512138, 520622, ...], 'Able Spacer + Sml/Med Mask': [1360, 5150, 6718, 11976, 18723, 28241, 49414, 54167, 63081, 68501, 81226, 111311, 140199, 149958, 164855, 168452, 176723, 178235, 179986, 239634, 241422, 243357, 248838, 255027, 260389, 264212, 267979, 290234, 293751, 298877, 306948, 309617, 310889, 316540, 325697, 335099, 340701, 352625, 354026, 366283, 375277, 378253, 379570, 401701, 402954, 408502, 410111, 437681, 439417, 442686, 467725, 481870, 495810, 496936, 499257, 530362, 535458, 538134, 545997, 547034, 548665, 550214, 564773, 572568, 579473, 586791, 591816, 597332, 602174, 624250, 658985, 673028, 674988, 677058, 685603, 691581, 695746, 722608, 732668, 745898, 752461, 754340, 762811, 775969, 776712, 777604, 780203, 782070, 796853, 800657, 802221, 804418, 804650, 807498, 811426, 811965, 816620, 817970, 819097, 827465, ...], 'Absorbent Cott Gz 90cm x 1m Ster': [846229], 'Absorbent Cott Gz 90cm x 5m Ster': [435701, 846230], 'Absorbent Cott Wool BP 100g': [11918, 264125, 402933, 566368, 595023, 688982, 932157], 'Absorbent Cott Wool BP 25g': [77650, 709375], 'Absorbent Cott Wool BP 500g': [82895, 125489, 239566, 343353, 348153, 363057, 450860, 553663, 564723, 579380, 600934, 707697, 713736, 841457, 883333, 887243, 914152, 953613, 957194], 'Absorbent Cott Wool HQ 500g': [687408, 785872, 962385], 'Abstral_Tab Sublingual 100mcg': [78415, 119611, 177399, 506254, 611900, 630702, 653056, 664173, 841999, 963197, 966392, 967817], 'Abstral_Tab Sublingual 200mcg': [78416, 434722, 479070, 503001, 656976], 'Abstral_Tab Sublingual 300mcg': [355601, 642375], 'Abstral_Tab Sublingual 400mcg': [227920, 432615, 506255, 630703], 'Abstral_Tab Sublingual 800mcg': [696730], 'Abtard_Tab 10mg M/R': [162815, 203307, 242337, 247668, 573163, 708559, 710080], 'Abtard_Tab 15mg M/R': [242338, 247669, 573164], 'Abtard_Tab 20mg M/R': [242339, 247670, 270035, 337268, 706747, 710081], 'Abtard_Tab 30mg M/R': [247672, 573165, 710082], 'Abtard_Tab 40mg M/R': [177386, 242340, 247671], 'Abtard_Tab 5mg M/R': [242336, 706746, 812518], 'Abtard_Tab 60mg M/R': [242341], 'Abtard_Tab 80mg M/R': [247673], 'Acamprosate Calc_Tab E/C 333mg': [2316, 6025, 7630, 9077, 11169, 14231, 16013, 17865, 19860, 21462, 22645, 24537, 26045, 29396, 32578, 35277, 38484, 43591, 45841, 48567, 50249, 51770, 53506, 55019, 57779, 59543, 60939, 62421, 65723, 71521, 72769, 77097, 80359, 82218, 83705, 85177, 93510, 94940, 97287, 102593, 104257, 105828, 108150, 110852, 114322, 118298, 119754, 121018, 124811, 126449, 129327, 131837, 132972, 136682, 139201, 141144, 142976, 147116, 149556, 150465, 154362, 157367, 158371, 159049, 162236, 164167, 165665, 168133, 169049, 171485, 172652, 174003, 175175, 176209, 177537, 179215, 180804, 186149, 187764, 189338, 193119, 194791, 196633, 199818, 202313, 203416, 204516, 207033, 208496, 209996, 211570, 213900, 214902, 215800, 216897, 218245, 219158, 220057, 221791, 224105, ...], 'Acapella Oscillating Positive Expiratory': [11971, 94208, 100779, 221286, 375272, 413661, 436211, 454983, 615922, 628353, 781372, 928088], 'Acarbose_Tab 100mg': [50347, 69768, 137979, 182582, 185009, 233630, 275389, 280932, 291399, 298273, 300011, 301978, 397970, 406599, 424829, 430196, 443978, 445780, 458742, 473203, 477927, 513171, 516373, 616689, 620053, 645504, 692944, 725282, 748173, 755142, 760718, 778157, 801999, 810511, 834007, 848874, 854092, 856941, 884636, 891242, 915547, 949556, 954743, 961930, 970962], 'Acarbose_Tab 50mg': [2447, 11304, 16153, 20009, 21562, 22747, 24649, 31619, 33956, 35415, 38591, 43700, 44846, 67839, 69767, 71629, 80508, 90562, 92037, 93623, 96244, 104400, 110015, 114498, 117127, 119862, 124951, 126619, 137978, 149644, 152161, 169145, 177681, 179381, 193233, 196761, 198400, 202399, 217030, 229989, 231759, 233629, 238843, 251473, 259681, 261449, 263390, 267126, 274373, 276401, 277663, 280931, 300010, 301977, 306361, 311752, 314055, 323445, 329002, 331143, 358020, 362505, 365629, 371008, 373058, 385781, 397969, 409509, 426563, 428196, 430195, 432996, 442026, 458741, 461892, 465177, 474923, 477926, 479376, 481145, 492564, 503280, 506525, 513170, 516372, 521674, 546634, 547962, 557519, 580595, 586020, 592743, 610875, 612172, 613929, 618264, 623652, 629401, 630995, 632487, ...], 'Accolate_Tab 20mg': [17456, 24167, 79963, 162686, 233059, 285234, 317092, 332070, 502821, 510952, 517639, 547526, 611739, 619590, 640623, 659503, 698363, 919779], 'Accrete D3_Tab': [1037, 2730, 4711, 6387, 7996, 9385, 13052, 14628, 16448, 18291, 20312, 21715, 22946, 24928, 26335, 27872, 32891, 35696, 38815, 40145, 42575, 50548, 52202, 53849, 59949, 61733, 62748, 64326, 66234, 68072, 70114, 71859, 78938, 80786, 82557, 93852, 98785, 102955, 104649, 106133, 107303, 108404, 109415, 110118, 111094, 111957, 112900, 114812, 116182, 120047, 123705, 126888, 139703, 141550, 143471, 145072, 149760, 150662, 154658, 158515, 159233, 160180, 161432, 163134, 164533, 167284, 168310, 171699, 176483, 177919, 179635, 181183, 182882, 184104, 185179, 186525, 188174, 189668, 190687, 191959, 193456, 195247, 196994, 198616, 200157, 201327, 202546, 203676, 204782, 207371, 210365, 217292, 220270, 223175, 224345, 225310, 227039, 228472, 235448, 236429, ...], 'Accupro_Tab 10mg': [107756, 243768, 619332], 'Accupro_Tab 20mg': [290635], 'Accupro_Tab 40mg': [315479], 'Accuretic_Tab': [107754, 667260, 876853, 955792], 'Acea_Gel 0.75%': [36062, 107503, 115189, 140041, 167523, 227188, 398751, 594776, 653874, 683878, 887205, 891777, 905658], 'Acebut HCl_Cap 100mg': [5480, 10498, 15319, 181743, 187125, 191005, 286679, 292373, 295599, 307312, 319514, 343597, 379867, 577799, 619281, 649513, 677820, 684252, 706215, 759291, 766160, 812096, 816933, 840519, 864070, 919561, 920956, 922547, 924044, 932474, 941071, 942684, 947093], 'Acebut HCl_Cap 200mg': [15320, 43041, 77941, 113507, 119216, 181744, 183524, 185633, 241778, 247072, 295600, 316767, 319515, 347081, 348443, 370566, 379868, 472316, 489159, 504212, 601130, 610295, 638631, 644849, 656476, 677821, 704772, 709692, 715627, 783388, 813701, 904442, 922548, 932475, 941072, 948800, 952158, 961296], 'Acebut HCl_Tab 400mg': [19115, 36476, 67092, 140454, 142196, 165104, 190158, 194045, 234676, 245429, 253684, 278470, 491883, 550511, 615266, 622903, 630241, 635954, 638632, 685942, 706216, 820385, 941073, 948801], 'Aceclofenac_Tab 100mg': [66298, 70171, 78977, 84021, 93895, 125235, 141602, 153418, 182933, 197040, 207408, 211952, 243004, 244795, 275546, 277891, 306653, 309037, 312042, 383615, 418737, 430551, 433398, 669437, 677535, 687092, 816231, 821492, 850944, 860149, 872873, 910545, 935943, 963781], 'Acemetacin_Cap 60mg': [32936, 126933, 153417, 174348, 205951, 222060, 251779, 254723, 271808, 295034, 325431, 330242, 379291, 385964, 415328, 437376, 449111, 476868, 496728, 508549, 553387, 594566, 607809, 611104, 622353, 641308, 677534, 681990, 732444, 930573, 965390], 'Acenocoumarol_Tab 1mg': [3630, 5607, 7123, 15479, 19291, 21154, 25669, 27006, 43175, 69033, 76711, 103762, 106694, 111551, 113702, 125912, 130502, 133744, 140631, 162589, 166576, 171123, 174845, 181916, 184539, 187272, 188954, 191152, 199377, 205354, 222479, 224819, 229280, 231133, 238108, 243898, 245604, 250782, 257197, 259050, 262671, 272349, 275974, 288804, 294204, 303088, 311220, 316940, 322837, 328512, 336924, 339368, 341099, 380023, 384232, 411275, 422134, 434383, 445125, 485701, 487731, 507564, 544015, 568759, 571668, 593719, 596113, 602400, 604373, 613119, 630388, 631967, 643725, 647123, 648549, 656641, 659374, 663898, 677982, 679616, 692495, 696361, 698233, 736426, 746287, 748787, 751217, 804957, 809965, 817028, 836850, 839447, 858050, 875124, 887925, 890615, 904579, 906023, 907222, 912763, ...], 'Acetazolamide_Cap 250mg M/R': [4829, 13137, 25036, 27992, 35852, 58203, 79040, 84062, 92354, 103065, 104759, 108473, 114957, 139834, 143621, 184163, 192052, 197103, 234086, 243090, 250159, 254781, 258244, 261860, 265618, 271855, 281305, 284519, 287942, 291764, 297335, 306713, 309149, 313218, 314310, 317894, 323846, 327913, 356058, 368301, 374965, 402805, 408226, 411965, 425253, 426858, 433481, 435392, 440695, 456232, 476930, 479743, 481546, 482994, 486886, 488689, 492886, 496777, 503613, 518643, 527454, 540391, 542867, 553459, 581033, 584676, 589233, 590589, 593068, 599550, 600759, 601969, 605093, 607870, 612469, 614516, 639809, 643109, 654852, 656257, 660516, 661850, 671120, 683712, 685376, 700863, 705767, 707459, 712554, 715077, 722216, 723929, 725678, 733567, 770412, 771333, 785730, 788154, 803066, 813149, ...], 'Acetazolamide_Oral Susp 250mg/5ml': [418805, 488690, 522030, 893362], 'Acetazolamide_Tab 250mg': [2843, 8089, 18425, 20423, 38920, 49110, 55505, 58202, 62833, 64421, 66375, 68176, 85722, 90840, 93952, 103064, 104758, 114956, 116244, 120134, 121407, 123789, 127003, 128532, 129709, 134414, 143620

In [28]:
group_bnf.groups['A2A Spacer']

Int64Index([ 88619, 127274, 133463, 239632, 260387, 272065, 346756, 427043,
            428945, 487232, 522273, 657947, 660825, 662024, 663608, 707763,
            833153, 851265, 871681, 874636, 879990, 910747, 916306],
           dtype='int64')

In [29]:
scripts.loc[group_bnf.groups['A2A Spacer']]

       practice   bnf_code    bnf_name  items     nic  act_cost  quantity
88619    A81037  210102301  A2A Spacer      2    8.30      7.71         2
127274   P83603  210102301  A2A Spacer      2    8.30      7.71         2
133463   P84611  210102301  A2A Spacer      1    4.15      3.85         1
239632   P81072  210102301  A2A Spacer      1    4.15      3.85         1
260387   P81069  210102301  A2A Spacer      3   12.45     11.54         3
272065   P81215  210102301  A2A Spacer      1    4.15      3.85         1
346756   A84009  210102301  A2A Spacer      1    4.15      3.85         1
427043   C85019  210102301  A2A Spacer      1    4.15      3.85         1
428945   C85022  210102301  A2A Spacer      1    4.15      3.85         1
487232   M84012  210102301  A2A Spacer      1    4.15      3.85         1
522273   M81094  210102301  A2A Spacer      1    4.15      3.84         1
657947   K83013  210102301  A2A Spacer      7   33.20     30.81         8
660825   K83051  210102301  A2A Spacer     35  153.55    142.59        37
662024   K83076  210102301  A2A Spacer      3   12.45     11.56         3
663608   Y00234  210102301  A2A Spacer      4   16.60     15.41         4
707763   C82047  210102301  A2A Spacer     15   66.40     61.66        16
833153   G85012  210102301  A2A Spacer      1    4.15      3.85         1
851265   L84026  210102301  A2A Spacer      1    4.15      3.85         1
871681   Y03662  210102301  A2A Spacer      1    4.15      3.85         1
874636   L81043  210102301  A2A Spacer      1    8.30      7.70         2
879990   L85002  210102301  A2A Spacer      1    4.15      3.85         1
910747   G82791  210102301  A2A Spacer      1    4.15      3.85         1
916306   G82126  210102301  A2A Spacer      1    4.15      3.85         1

In [30]:
group_bnf.sum()

                                          items      nic  act_cost  quantity
bnf_name
365 Film 10cm x 12cm VP Adh Film Dress        2     6.40      5.95        40
365 Non Adherent 10cm x 10cm Pfa Plas Fa      3    11.70     10.87       130
365 Non Adherent 10cm x 20cm Pfa Plas Fa      1     4.25      3.95        25
365 Non Woven Island 8cm x 10cm Adh Dres      1     0.60      0.57        10
365 Transpt Island 5cm x 7.2cm VP Adh Fi      2     7.50      6.97       150
...                                         ...      ...       ...       ...
nSpire PiKo-1 Stnd Range Peak Flow Meter      1     9.50      8.81         1
nSpire Pocket Peak Low Range Peak Flow M      4    26.12     24.24         4
nSpire Pocket Peak Stnd Range Peak Flow       8    52.24     48.47         8
oraNurse_Toothpaste Orig (1450ppm)            4    19.20     17.83       600
palmdoc (Reagent)_Strips                     59  1005.80    931.72      5350

[13471 rows x 4 columns]

In [31]:
item_totals = group_bnf.sum()['items']
item_totals

bnf_name
365 Film 10cm x 12cm VP Adh Film Dress       2
365 Non Adherent 10cm x 10cm Pfa Plas Fa     3
365 Non Adherent 10cm x 20cm Pfa Plas Fa     1
365 Non Woven Island 8cm x 10cm Adh Dres     1
365 Transpt Island 5cm x 7.2cm VP Adh Fi     2
                                            ..
nSpire PiKo-1 Stnd Range Peak Flow Meter     1
nSpire Pocket Peak Low Range Peak Flow M     4
nSpire Pocket Peak Stnd Range Peak Flow      8
oraNurse_Toothpaste Orig (1450ppm)           4
palmdoc (Reagent)_Strips                    59
Name: items, Length: 13471, dtype: int64

In [32]:
item_totals.sort_values(ascending=False)

bnf_name
Omeprazole_Cap E/C 20mg                     218583
Paracet_Tab 500mg                           151669
Aspirin Disper_Tab 75mg                     148591
Simvastatin_Tab 40mg                        132941
Amlodipine_Tab 5mg                          128245
                                             ...
Quest_Cell Life Antiox Tab                       1
Quest_Lactase Tab                                1
Juzo Soft Rib Style Class 1 B/Knee Close         1
Quetiapine_Oral Soln 12.5mg/5ml                  1
ReadyWrap Gauntlet Lymph Gmt                     1
Name: items, Length: 13471, dtype: int64

In [33]:
item_totals.sort_values(ascending=False).index[0]

'Omeprazole_Cap E/C 20mg'

In [34]:
item_totals.sort_values(ascending=False)[0]

218583

In [35]:
#most_common_item = [(item_totals.sort_values(ascending=False).index[0],item_totals.sort_values(ascending=False)[0])]

In [36]:
max_item = item_totals.idxmax()
max_item
# idxmax() - it returns the index label of the max value

'Omeprazole_Cap E/C 20mg'

In [37]:
most_common_item = [(max_item,item_totals.loc[max_item])]
most_common_item

[('Omeprazole_Cap E/C 20mg', 218583)]

In [38]:
grader.score.dw__most_common_item(most_common_item)

==================
Your score: 1.000
==================

## Question 3: items_by_region

Now let's find the most common item by post code. The post code information is in the `practices` DataFrame, and we'll need to `merge` it into the `scripts` DataFrame. Pandas provides [extensive documentation](https://pandas.pydata.org/pandas-docs/stable/merging.html) with diagrammed examples on different methods and approaches for joining data. The `merge` method is only one of many possible options.

Return your results as a list of tuples `(post code, item name, amount dispensed as % of total)`. Sort your results ascending alphabetically by post code and take only results from the first 100 post codes.

**NOTE:** Some practices have multiple postal codes associated with them. Use the alphabetically first postal code. Note some postal codes may have multiple `'bnf_name'` with the same prescription rate for the maximum. In this case, take the alphabetically first `'bnf_name'` (as in the `pw` miniproject).

In [39]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [40]:
practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,NaN,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [41]:
practices.sort_values('post_code').groupby('code').first().head()
# first sort the dataset by postcode and then groupby code and
# if one code(hospital) has many records then select first one
#(which is the alphabeticlly first by postcode)

,name,addr_1,addr_2,borough,village,post_code
code,,,,,,
A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
A81003,VICTORIA MEDICAL PRACTICE,MCKENZIE HOUSE,17 KENDAL ROAD,HARTLEPOOL,CLEVELAND,TS25 1QU
A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,ACKLAM,MIDDLESBROUGH,CLEVELAND,TS1 3BE
A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [42]:
practices[practices['code']=='A81003'] #code with multiple records
#our above code is right since in the result it is TS25 1QU.

,code,name,addr_1,addr_2,borough,village,post_code
2,A81003,VICTORIA MEDICAL PRACTICE,THE HEALTH CENTRE,VICTORIA ROAD,HARTLEPOOL,CLEVELAND,TS26 8DB
11057,A81003,VICTORIA MEDICAL PRACTICE,MCKENZIE HOUSE,17 KENDAL ROAD,HARTLEPOOL,CLEVELAND,TS25 1QU

In [43]:
unique_practices = practices.sort_values('post_code').groupby('code').first().reset_index()
unique_practices.head()

,code,name,addr_1,addr_2,borough,village,post_code
0,A81001,THE DENSHAM SURGERY,THE HEALTH CENTRE,LAWSON STREET,STOCKTON ON TEES,CLEVELAND,TS18 1HU
1,A81002,QUEENS PARK MEDICAL CENTRE,QUEENS PARK MEDICAL CTR,FARRER STREET,STOCKTON ON TEES,CLEVELAND,TS18 2AW
2,A81003,VICTORIA MEDICAL PRACTICE,MCKENZIE HOUSE,17 KENDAL ROAD,HARTLEPOOL,CLEVELAND,TS25 1QU
3,A81004,WOODLANDS ROAD SURGERY,6 WOODLANDS ROAD,ACKLAM,MIDDLESBROUGH,CLEVELAND,TS1 3BE
4,A81005,SPRINGWOOD SURGERY,SPRINGWOOD SURGERY,RECTORY LANE,GUISBOROUGH,NaN,TS14 7DJ

In [44]:
scripts.merge(unique_practices,how='left',left_on ='practice',right_on='code')

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,code,name,addr_1,addr_2,borough,village,post_code
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,N85639,GP OOH VCH,VICTORIA CENTRAL HOSPITAL,MILL LANE,WALLASEY,NaN,CH44 5UF
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30,N85639,GP OOH VCH,VICTORIA CENTRAL HOSPITAL,MILL LANE,WALLASEY,NaN,CH44 5UF
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1,N85639,GP OOH VCH,VICTORIA CENTRAL HOSPITAL,MILL LANE,WALLASEY,NaN,CH44 5UF
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150,N85639,GP OOH VCH,VICTORIA CENTRAL HOSPITAL,MILL LANE,WALLASEY,NaN,CH44 5UF
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6,N85639,GP OOH VCH,VICTORIA CENTRAL HOSPITAL,MILL LANE,WALLASEY,NaN,CH44 5UF
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
973188,H81615,239410100,Coloplast_SenSura Mio Flex B/Plt 50mm C/,1,78.92,73.06,20,H81615,FARNHAM DENE MEDICAL PRACTICE,FARNHAM CENTRE FOR HEALTH,HALE ROAD,FARNHAM,SURREY,GU9 9QS
973189,H81615,239410100,Coloplast_SenSura Mio Flex Clsd Bag Mini,1,106.36,98.46,60,H81615,FARNHAM DENE MEDICAL PRACTICE,FARNHAM CENTRE FOR HEALTH,HALE ROAD,FARNHAM,SURREY,GU9 9QS
973190,H81615,239410100,Coloplast_SenSura Mio Flex Clsd Bag Midi,1,159.54,147.69,90,H81615,FARNHAM DENE MEDICAL PRACTICE,FARNHAM CENTRE FOR HEALTH,HALE ROAD,FARNHAM,SURREY,GU9 9QS
973191,H81615,239607096,Dansac_Nova 1 Convex Urost Pouch Clr C/F,2,329.76,305.28,60,H81615,FARNHAM DENE MEDICAL PRACTICE,FARNHAM CENTRE FOR HEALTH,HALE ROAD,FARNHAM,SURREY,GU9 9QS
973192,H81615,239610096,Coloplast_SenSura Mio Urost Bag Maxi Tra,1,182.48,168.93,30,H81615,FARNHAM DENE MEDICAL PRACTICE,FARNHAM CENTRE FOR HEALTH,HALE ROAD,FARNHAM,SURREY,GU9 9QS

In [45]:
#merging the sliced dataframes
scripts[['practice','bnf_name','items']].merge(unique_practices[['code','post_code']],how='left',left_on ='practice',right_on='code')

,practice,bnf_name,items,code,post_code
0,N85639,Bisacodyl_Tab E/C 5mg,1,N85639,CH44 5UF
1,N85639,Movicol Plain_Paed Pdr Sach 6.9g,1,N85639,CH44 5UF
2,N85639,Salbutamol_Inha 100mcg (200 D) CFF,1,N85639,CH44 5UF
3,N85639,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,N85639,CH44 5UF
4,N85639,Diazepam_Tab 2mg,1,N85639,CH44 5UF
...,...,...,...,...,...
973188,H81615,Coloplast_SenSura Mio Flex B/Plt 50mm C/,1,H81615,GU9 9QS
973189,H81615,Coloplast_SenSura Mio Flex Clsd Bag Mini,1,H81615,GU9 9QS
973190,H81615,Coloplast_SenSura Mio Flex Clsd Bag Midi,1,H81615,GU9 9QS
973191,H81615,Dansac_Nova 1 Convex Urost Pouch Clr C/F,2,H81615,GU9 9QS
973192,H81615,Coloplast_SenSura Mio Urost Bag Maxi Tra,1,H81615,GU9 9QS

####### on slicing the above dataframe further we get the                 dataframe with the required columns.

In [46]:
joined = scripts[['practice','bnf_name','items']].merge(unique_practices[['code','post_code']],how='left',left_on ='practice',right_on='code')[['bnf_name','items','post_code']]

In [47]:
joined.head()

                               bnf_name  items post_code
0                 Bisacodyl_Tab E/C 5mg      1  CH44 5UF
1      Movicol Plain_Paed Pdr Sach 6.9g      1  CH44 5UF
2    Salbutamol_Inha 100mcg (200 D) CFF      1  CH44 5UF
3  Chlorphenamine Mal_Oral Soln 2mg/5ml      1  CH44 5UF
4                      Diazepam_Tab 2mg      1  CH44 5UF

In [48]:
joined.groupby(['post_code','bnf_name']).sum()

                                                    items
post_code bnf_name
B11 4BW   3m Health Care_Cavilon Durable Barrier C      7
          3m Health Care_Cavilon No Sting Barrier       2
          Abasaglar KwikPen_100u/ml 3ml Pf Pen          2
          Abidec_Dps                                   63
          Able Spacer + Sml/Med Mask                    1
...                                                   ...
YO16 4LZ  Zydol SR_Tab 50mg                             1
          easiGRIP 12cm x 1m Stkntte Elasctd Tublr      1
          iMEDicare SomaCorrect Xtra Vacuum Pump        1
          iMEDicare_Urine Collection Bag 500ml          1
          kliniderm superabsorbent 20cm x 30cm Pfa      1

[579197 rows x 1 columns]

In [49]:
post_item_totals = joined.groupby(['post_code','bnf_name']).sum().reset_index()
post_item_totals

       post_code                                  bnf_name  items
0        B11 4BW  3m Health Care_Cavilon Durable Barrier C      7
1        B11 4BW   3m Health Care_Cavilon No Sting Barrier      2
2        B11 4BW      Abasaglar KwikPen_100u/ml 3ml Pf Pen      2
3        B11 4BW                                Abidec_Dps     63
4        B11 4BW                Able Spacer + Sml/Med Mask      1
...          ...                                       ...    ...
579192  YO16 4LZ                         Zydol SR_Tab 50mg      1
579193  YO16 4LZ  easiGRIP 12cm x 1m Stkntte Elasctd Tublr      1
579194  YO16 4LZ    iMEDicare SomaCorrect Xtra Vacuum Pump      1
579195  YO16 4LZ      iMEDicare_Urine Collection Bag 500ml      1
579196  YO16 4LZ  kliniderm superabsorbent 20cm x 30cm Pfa      1

[579197 rows x 3 columns]

In [50]:
max_items = post_item_totals.sort_values('items',ascending=False).groupby('post_code').first()

In [51]:
max_items

                                     bnf_name  items
post_code
B11 4BW    Salbutamol_Inha 100mcg (200 D) CFF    706
B12 9LP                     Paracet_Tab 500mg    425
B18 7AL    Salbutamol_Inha 100mcg (200 D) CFF    556
B21 9RY               Metformin HCl_Tab 500mg   1033
B23 6DJ      Lansoprazole_Cap 30mg (E/C Gran)    599
...                                       ...    ...
WS3 3JP                     Paracet_Tab 500mg    789
WS9 8AJ                    Amlodipine_Tab 5mg    396
WV13 2DR   Salbutamol_Inha 100mcg (200 D) CFF    809
YO11 1UB              Omeprazole_Cap E/C 20mg    847
YO16 4LZ              Aspirin Disper_Tab 75mg   1194

[259 rows x 2 columns]

In [52]:
max_items['items']

post_code
B11 4BW      706
B12 9LP      425
B18 7AL      556
B21 9RY     1033
B23 6DJ      599
            ...
WS3 3JP      789
WS9 8AJ      396
WV13 2DR     809
YO11 1UB     847
YO16 4LZ    1194
Name: items, Length: 259, dtype: int64

In [53]:
post_item_totals.groupby('post_code')['items'].sum()

post_code
B11 4BW     22731
B12 9LP     17073
B18 7AL     20508
B21 9RY     31027
B23 6DJ     28011
            ...
WS3 3JP     36890
WS9 8AJ     24483
WV13 2DR    36381
YO11 1UB    28507
YO16 4LZ    53847
Name: items, Length: 259, dtype: int64

In [54]:
max_items['items']/post_item_totals.groupby('post_code')['items'].sum()

post_code
B11 4BW     0.031059
B12 9LP     0.024893
B18 7AL     0.027111
B21 9RY     0.033294
B23 6DJ     0.021384
              ...
WS3 3JP     0.021388
WS9 8AJ     0.016174
WV13 2DR    0.022237
YO11 1UB    0.029712
YO16 4LZ    0.022174
Name: items, Length: 259, dtype: float64

In [55]:
max_items['items']=max_items['items']/post_item_totals.groupby('post_code')['items'].sum()

In [56]:
max_items.head()

                                     bnf_name     items
post_code
B11 4BW    Salbutamol_Inha 100mcg (200 D) CFF  0.031059
B12 9LP                     Paracet_Tab 500mg  0.024893
B18 7AL    Salbutamol_Inha 100mcg (200 D) CFF  0.027111
B21 9RY               Metformin HCl_Tab 500mg  0.033294
B23 6DJ      Lansoprazole_Cap 30mg (E/C Gran)  0.021384

In [57]:
max_items = max_items.reset_index().sort_values('post_code') #mistake recorrected

In [58]:
max_items

    post_code                            bnf_name     items
0     B11 4BW  Salbutamol_Inha 100mcg (200 D) CFF  0.031059
1     B12 9LP                   Paracet_Tab 500mg  0.024893
2     B18 7AL  Salbutamol_Inha 100mcg (200 D) CFF  0.027111
3     B21 9RY             Metformin HCl_Tab 500mg  0.033294
4     B23 6DJ    Lansoprazole_Cap 30mg (E/C Gran)  0.021384
..        ...                                 ...       ...
254   WS3 3JP                   Paracet_Tab 500mg  0.021388
255   WS9 8AJ                  Amlodipine_Tab 5mg  0.016174
256  WV13 2DR  Salbutamol_Inha 100mcg (200 D) CFF  0.022237
257  YO11 1UB             Omeprazole_Cap E/C 20mg  0.029712
258  YO16 4LZ             Aspirin Disper_Tab 75mg  0.022174

[259 rows x 3 columns]

In [59]:
items_by_region = [(item[1:]) for item in max_items.itertuples()][:100]

In [60]:
items_by_region

[('B11 4BW', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.031058906339360346),
 ('B12 9LP', 'Paracet_Tab 500mg', 0.02489310607391788),
 ('B18 7AL', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.027111371172225472),
 ('B21 9RY', 'Metformin HCl_Tab 500mg', 0.03329358300834757),
 ('B23 6DJ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021384456106529576),
 ('B61 0AZ', 'Omeprazole_Cap E/C 20mg', 0.028713318284424378),
 ('B70 7AW', 'Paracet_Tab 500mg', 0.025135992162726547),
 ('B72 1RL', 'Omeprazole_Cap E/C 20mg', 0.020228765092141495),
 ('B8 1RZ', 'Metformin HCl_Tab 500mg', 0.021347750961484866),
 ('B9 5PU', 'Ventolin_Evohaler 100mcg (200 D)', 0.024826024522257815),
 ('B90 3LX', 'Omeprazole_Cap E/C 20mg', 0.026965103983080718),
 ('BA5 1XJ', 'Omeprazole_Cap E/C 20mg', 0.028261290947858113),
 ('BB11 2DL', 'Omeprazole_Cap E/C 20mg', 0.027381741821396993),
 ('BB2 1AX', 'Omeprazole_Cap E/C 20mg', 0.03428191046763188),
 ('BB3 1PY', 'Omeprazole_Cap E/C 20mg', 0.032683395995453356),
 ('BB4 5SL', 'Omeprazole_Cap E/C 20mg', 0.03747689029549087),
 ('BB4 7PL', 'Omeprazole_Cap E/C 20mg', 0.027477496877557173),
 ('BB7 2JG', 'Omeprazole_Cap E/C 20mg', 0.027980664806967485),
 ('BB8 0JZ', 'Atorvastatin_Tab 20mg', 0.021515746650768042),
 ('BB9 7SR', 'Omeprazole_Cap E/C 20mg', 0.02247662283190644),
 ('BD16 4RP', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.022780283004198414),
 ('BD19 5AP', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.02066220372715759),
 ('BD3 8QH', 'Atorvastatin_Tab 40mg', 0.031662850096882154),
 ('BD4 7SS', 'Atorvastatin_Tab 40mg', 0.03424183501960914),
 ('BH14 0DJ', 'Omeprazole_Cap E/C 20mg', 0.02838931332218254),
 ('BH18 8EE', 'Omeprazole_Cap E/C 20mg', 0.027092370049064923),
 ('BH23 3AF', 'Omeprazole_Cap E/C 20mg', 0.03546099290780142),
 ('BL1 3RG', 'Omeprazole_Cap E/C 20mg', 0.03362566656383588),
 ('BL1 8TU', 'Omeprazole_Cap E/C 20mg', 0.027729220222793487),
 ('BL2 6NT', 'Omeprazole_Cap E/C 20mg', 0.0271567320510379),
 ('BL3 5HP', 'Omeprazole_Cap E/C 20mg', 0.03129933420275929),
 ('BL9 0NJ', 'Omeprazole_Cap E/C 20mg', 0.032037565382786494),
 ('BL9 0SN', 'Omeprazole_Cap E/C 20mg', 0.03090454288711369),
 ('BN1 6AG', 'Lansoprazole_Cap 15mg (E/C Gran)', 0.021755523716160168),
 ('BN1 8DD', 'Aspirin Disper_Tab 75mg', 0.021517850460294887),
 ('BN9 9PW', 'Omeprazole_Cap E/C 20mg', 0.01855317763853853),
 ('BR2 9GT', 'Influenza_Vac Inact 0.5ml Pfs', 0.04301700334253742),
 ('BR3 3FD', 'Omeprazole_Cap E/C 20mg', 0.02865911645197545),
 ('BS16 3TD', 'Omeprazole_Cap E/C 20mg', 0.03752737892431249),
 ('BS23 3HQ', 'Omeprazole_Cap E/C 20mg', 0.030246216399367518),
 ('BS4 1WH', 'Omeprazole_Cap E/C 20mg', 0.029600778967867575),
 ('BS4 4HU', 'Omeprazole_Cap E/C 20mg', 0.037361354349095155),
 ('BS48 2XX', 'Omeprazole_Cap E/C 20mg', 0.030207346595095254),
 ('CA11 8HW', 'Omeprazole_Cap E/C 20mg', 0.027868623340321454),
 ('CB22 3HU', 'Omeprazole_Cap E/C 20mg', 0.038775726713346066),
 ('CB9 8HF', 'Omeprazole_Cap E/C 20mg', 0.03391110538046382),
 ('CH1 4DS', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.0257736189772634),
 ('CH41 8DB', 'Omeprazole_Cap E/C 20mg', 0.03327732469980738),
 ('CH44 5UF', 'Omeprazole_Cap E/C 20mg', 0.03327334826839032),
 ('CH62 5HS', 'Omeprazole_Cap E/C 20mg', 0.037778835690968446),
 ('CH62 6EE', 'Influenza_Vac Inact 0.5ml Pfs', 0.057585894269547),
 ('CH65 6TG', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.026067517902474142),
 ('CH66 3PB', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.03100619319552803),
 ('CM18 6LY', 'Omeprazole_Cap E/C 20mg', 0.026445315758738635),
 ('CR0 0JA', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.021571724750715768),
 ('CT11 8AD', 'Omeprazole_Cap E/C 20mg', 0.022307039864291774),
 ('CV1 4FS', 'Omeprazole_Cap E/C 20mg', 0.028455180531743392),
 ('CV12 8NQ', 'Omeprazole_Cap E/C 20mg', 0.026444799282852902),
 ('CV21 2DN', 'Omeprazole_Cap E/C 20mg', 0.04102890311294875),
 ('CV6 2FL', 'Omeprazole_Cap E/C 20mg', 0.036250663502669624),
 ('CV6 6DR', 'Omeprazole_Cap E/C 20mg', 0.030544721504009817),
 ('CW1 3AW', 'Omeprazole_Cap E/C 20mg', 0.03558258199497268),
 ('CW5 5NX', 'Omeprazole_Cap E/C 20mg', 0.03453647138997736),
 ('CW7 1AT', 'Omeprazole_Cap E/C 20mg', 0.03666371289322109),
 ('DA1 2HA', 'Omeprazole_Cap E/C 20mg', 0.019244977658938185),
 ('DA11 8BZ', 'Amoxicillin_Cap 500mg', 0.019686834904226208),
 ('DN16 2AB', 'Amlodipine_Tab 5mg', 0.019925280199252802),
 ('DN22 7XF', 'Simvastatin_Tab 40mg', 0.018624361621210474),
 ('DN31 3AE', 'Omeprazole_Cap E/C 20mg', 0.03432952436761402),
 ('DN34 4GB', 'Omeprazole_Cap E/C 20mg', 0.03709507845509909),
 ('DN6 0HZ', 'Paracet_Tab 500mg', 0.025764099668243102),
 ('DN8 4BQ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021703061442945835),
 ('DY11 6SF', 'Omeprazole_Cap E/C 20mg', 0.021081859317153433),
 ('E15 4ES', 'Amlodipine_Tab 10mg', 0.02569068641412703),
 ('E7 0EP', 'Metformin HCl_Tab 500mg', 0.037244933982913224),
 ('FY2 0JG', 'Omeprazole_Cap E/C 20mg', 0.03627638093657511),
 ('FY4 1TJ', 'Omeprazole_Cap E/C 20mg', 0.04334478808705613),
 ('FY5 2TZ', 'Omeprazole_Cap E/C 20mg', 0.03540407051009112),
 ('FY5 3LF', 'Omeprazole_Cap E/C 20mg', 0.035122866094073016),
 ('FY7 8GU', 'Omeprazole_Cap E/C 20mg', 0.032058079778122195),
 ('FY8 5DZ', 'Omeprazole_Cap E/C 20mg', 0.02969960416717259),
 ('GL1 3PX', 'Omeprazole_Cap E/C 20mg', 0.025687801991914012),
 ('GL20 5GJ', 'Omeprazole_Cap E/C 20mg', 0.02412690753362688),
 ('GL50 4DP', 'Omeprazole_Cap E/C 20mg', 0.024009042366605605),
 ('GU9 9QS', 'Omeprazole_Cap E/C 20mg', 0.027052485943893322),
 ('HA0 4UZ', 'Metformin HCl_Tab 500mg', 0.027855843941147297),
 ('HA3 7LT', 'Omeprazole_Cap E/C 20mg', 0.02504635488712953),
 ('HD6 1AT', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.021017471736896196),
 ('HG1 5AR', 'Omeprazole_Cap E/C 20mg', 0.02842489568845619),
 ('HR1 2JB', 'Omeprazole_Cap E/C 20mg', 0.028529603122966818),
 ('HR6 8HD', 'Omeprazole_Cap E/C 20mg', 0.027207967812149594),
 ('HU7 4DW', 'Salbutamol_Inha 100mcg (200 D) CFF', 0.025607843137254904),
 ('HU9 2LJ', 'Lansoprazole_Cap 30mg (E/C Gran)', 0.0243192109011288),
 ('IG7 4DF', 'Amlodipine_Tab 5mg', 0.01956475808155504),
 ('IP22 4WG', 'Omeprazole_Cap E/C 20mg', 0.02851095218241878),
 ('KT12 3LB', 'Omeprazole_Cap E/C 20mg', 0.01828471919895516),
 ('KT14 6DH', 'Amlodipine_Tab 5mg', 0.018667887710894296),
 ('KT16 8HZ', 'Amlodipine_Tab 5mg', 0.019319714781268066),
 ('KT6 6EZ', 'Omeprazole_Cap E/C 20mg', 0.02821316614420063),
 ('L31 0DJ', 'Omeprazole_Cap E/C 20mg', 0.029425653739448675)]

In [61]:
#items_by_region = [("B11 4BW", "Salbutamol_Inha 100mcg (200 D) CFF", 0.0310589063)] * 100

In [62]:
grader.score.dw__items_by_region(items_by_region)

==================
Your score: 1.000
==================

In [63]:
max_items.to_csv('dw-data/max_items.csv') 
#writing the ouput to a csv file

In [64]:
import dill

In [65]:
with open('dw-data/max_items.dill','wb')as f:
    dill.dump(max_items,f)
#writing the data in max_items to a binary file max_items.dill

In [66]:
with open('dw-data/max_items.dill','rb')as f:
    new_max_items = dill.load(f)
#loading the data in max_items.dill(binary form) into 
#new dataframe called new_max_items.

In [67]:
new_max_items.head()

  post_code                            bnf_name     items
0   B11 4BW  Salbutamol_Inha 100mcg (200 D) CFF  0.031059
1   B12 9LP                   Paracet_Tab 500mg  0.024893
2   B18 7AL  Salbutamol_Inha 100mcg (200 D) CFF  0.027111
3   B21 9RY             Metformin HCl_Tab 500mg  0.033294
4   B23 6DJ    Lansoprazole_Cap 30mg (E/C Gran)  0.021384

In [68]:
np.all(max_items == new_max_items)
#checking whether 2 dataframes are equal or not

True

## Question 4: script_anomalies

Drug abuse is a source of human and monetary costs in health care. A first step in identifying practitioners that enable drug abuse is to look for practices where commonly abused drugs are prescribed unusually often. Let's try to find practices that prescribe an unusually high amount of opioids. The opioids we'll look for are given in the list below.

In [69]:
opioids = ['morphine', 'oxycodone', 'methadone', 'fentanyl', 'pethidine', 'buprenorphine', 'propoxyphene', 'codeine']

These are generic names for drugs, not brand names. Generic drug names can be found using the `'bnf_code'` field in `scripts` along with the `chem` table. Use the list of opioids provided above along with these fields to make a new field in the `scripts` data that flags whether the row corresponds with a opioid prescription.

In [70]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6

In [71]:
chem.head()

    CHEM SUB                                NAME
0  0101010A0                     Alexitol Sodium
1  0101010B0                          Almasilate
2  0101010C0                 Aluminium Hydroxide
3  0101010D0  Aluminium Hydroxide With Magnesium
4  0101010E0                        Hydrotalcite

In [72]:
'|'.join(opioids) 
#'|'symbol is vertical line in keyboard

'morphine|oxycodone|methadone|fentanyl|pethidine|buprenorphine|propoxyphene|codeine'

In [73]:
chem['NAME'].str.contains('|'.join(opioids), case=False)

0       False
1       False
2       False
3       False
4       False
        ...
3482    False
3483    False
3484    False
3485    False
3486    False
Name: NAME, Length: 3487, dtype: bool

In [74]:
chem[chem['NAME'].str.contains('|'.join(opioids), case=False)]

       CHEM SUB                                      NAME
88    0104020D0       Codeine Phosphate Compound Mixtures
91    0104020N0                          Opium & Morphine
691   0309010C0                         Codeine Phosphate
693   0309010N0                 Diamorphine Hydrochloride
695   0309010S0                   Methadone Hydrochloride
701   0309020AC                        Guaiacol & Codeine
955   0407010F0     Co-Codamol (Codeine Phos/Paracetamol)
959   0407010M0        Co-Codaprin (Codeine Phos/Aspirin)
960   0407010N0      Co-Dydramol (Dihydrocodeine/Paracet)
963   0407010R0  Aspirin Phenacetin & Codeine(Codeine Co)
965   0407010T0             Aspirin Paracetamol & Codeine
967   0407010V0           Paracetamol & Codeine Phosphate
977   0407020AD                   Oxycodone Hydrochloride
978   0407020AE           Diamorphine Hydrochloride (Top)
979   0407020AF                Oxycodone HCl/Naloxone HCl
981   0407020A0                                  Fentanyl
982   0407020B0                             Buprenorphine
983   0407020C0                         Codeine Phosphate
985   0407020E0                        Dextropropoxyphene
986   0407020G0                   Dihydrocodeine Tartrate
989   0407020K0      Diamorphine Hydrochloride (Systemic)
991   0407020M0                   Methadone Hydrochloride
992   0407020N0                                  Morphine
993   0407020P0                    Morphine Hydrochloride
994   0407020Q0                          Morphine Sulfate
997   0407020V0                   Pethidine Hydrochloride
1001  0407020Z0                                 Oxycodone
1002  040702010                        Morphine Anhydrous
1003  040702020    Morphine Tartrate & Cyclizine Tartrate
1072  0409010A0                 Apomorphine Hydrochloride
1114  0410030A0               Buprenorphine Hydrochloride
1116  0410030C0                   Methadone Hydrochloride
1816  0704050G0                 Apomorphine Hydrochloride
3246  1501043F0                          Fentanyl Citrate
3276  1502010Z0  Bupivacaine Hydrochloride & Fentanyl Cit

In [75]:
opioid_codes = chem[chem['NAME'].str.contains('|'.join(opioids), case=False)]['CHEM SUB'].unique()
opioid_codes

array(['0104020D0', '0104020N0', '0309010C0', '0309010N0', '0309010S0',
       '0309020AC', '0407010F0', '0407010M0', '0407010N0', '0407010R0',
       '0407010T0', '0407010V0', '0407020AD', '0407020AE', '0407020AF',
       '0407020A0', '0407020B0', '0407020C0', '0407020E0', '0407020G0',
       '0407020K0', '0407020M0', '0407020N0', '0407020P0', '0407020Q0',
       '0407020V0', '0407020Z0', '040702010', '040702020', '0409010A0',
       '0410030A0', '0410030C0', '0704050G0', '1501043F0', '1502010Z0'],
      dtype=object)

In [76]:
scripts['bnf_code'].isin(opioid_codes)

0         False
1         False
2         False
3         False
4         False
          ...
973188    False
973189    False
973190    False
973191    False
973192    False
Name: bnf_code, Length: 973193, dtype: bool

In [77]:
scripts['bnf_code'].isin(opioid_codes).sum()
# It gives the number of opioids in scripts dataframe

34843

In [78]:
scripts['opioid'] = scripts['bnf_code'].isin(opioid_codes)
#adding new column 'opioid'to the scripts dataframe

In [79]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,opioid
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,False
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30,False
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1,False
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150,False
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6,False

In [80]:
scripts['opioid'].mean()#3.6% prescribtions are opioids

0.03580276471367961

In [81]:
scripts['opioid'].sum()#34843 prescriptions are opioids

34843

Now for each practice calculate the proportion of its prescriptions containing opioids.

**Hint:** Consider the following list: `[0, 1, 1, 0, 0, 0]`. What proportion of the entries are 1s? What is the mean value?

In [82]:
opioids_per_practice = scripts.groupby('practice')['opioid'].mean()

In [83]:
opioids_per_practice

practice
A81005    0.033179
A81007    0.043329
A81011    0.046556
A81012    0.042793
A81017    0.038140
            ...
Y05570    0.090909
Y05583    0.000000
Y05597    0.000000
Y05660    0.023055
Y05670    0.000000
Name: opioid, Length: 856, dtype: float64

How do these proportions compare to the overall opioid prescription rate? Subtract off the proportion of all prescriptions that are opioids from each practice's proportion.

In [84]:
relative_opioids_per_practice = opioids_per_practice - scripts['opioid'].mean()

In [85]:
relative_opioids_per_practice

practice
A81005   -0.002624
A81007    0.007526
A81011    0.010753
A81012    0.006990
A81017    0.002337
            ...
Y05570    0.055106
Y05583   -0.035803
Y05597   -0.035803
Y05660   -0.012748
Y05670   -0.035803
Name: opioid, Length: 856, dtype: float64

Now that we know the difference between each practice's opioid prescription rate and the overall rate, we can identify which practices prescribe opioids at above average or below average rates. However, are the differences from the overall rate important or just random deviations? In other words, are the differences from the overall rate big or small?

To answer this question we have to quantify the difference we would typically expect between a given practice's opioid prescription rate and the overall rate. This quantity is called the **standard error**, and is related to the **standard deviation**, $\sigma$. The standard error in this case is

$$ \frac{\sigma}{\sqrt{n}} $$

where $n$ is the number of prescriptions each practice made. Calculate the standard error for each practice. Then divide `relative_opioids_per_practice` by the standard errors. We'll call the final result `opioid_scores`.

In [86]:
scripts['opioid'].var()
#𝜎2  corresponds with the variance of the proportion across
#all practices

0.03452096222439277

In [87]:
standard_error_per_practice = np.sqrt(scripts['opioid'].var()/scripts['practice'].value_counts())
#standard error  also equals =sqrt(variance/n)
opioid_scores = relative_opioids_per_practice/standard_error_per_practice

In [88]:
standard_error_per_practice

N83028    0.003484
L83100    0.003513
D81043    0.003747
B81008    0.003796
B81026    0.003835
            ...
C85617    0.185798
Y03010    0.185798
Y01174    0.185798
Y03179    0.185798
Y03472    0.185798
Name: practice, Length: 856, dtype: float64

In [89]:
opioid_scores  # Z-scores for each hospital or practice

A81005   -0.548306
A81007    1.544557
A81011    2.291795
A81012    1.373060
A81017    0.583168
            ...
Y05570    1.391142
Y05583   -1.019657
Y05597   -0.817544
Y05660   -1.278102
Y05670   -0.667522
Length: 856, dtype: float64

The quantity we have calculated in `opioid_scores` is called a **z-score**:

$$ \frac{\bar{X} - \mu}{\sqrt{\sigma^2/n}} $$

Here $\bar{X}$ corresponds with the proportion for each practice, $\mu$ corresponds with the proportion across all practices, $\sigma^2$ corresponds with the variance of the proportion across all practices, and $n$ is the number of prescriptions made by each practice. Notice $\bar{X}$ and $n$ will be different for each practice, while $\mu$ and $\sigma$ are determined across all prescriptions, and so are the same for every z-score. The z-score is a useful statistical tool used for hypothesis testing, finding outliers, and comparing data about different types of objects or events.

Now that we've calculated this statistic, take the 100 practices with the largest z-score. Return your result as a list of tuples in the form `(practice_code, practice_name, z-score, number_of_scripts)`. Sort your tuples by z-score in descending order. Note that some practice codes will correspond with multiple names. In this case, use the first match when sorting names alphabetically.

In [90]:
unique_practices_by_name = practices.groupby('code')['name'].min().reset_index()

In [91]:
unique_practices_by_name.head()

     code                        name
0  A81001         THE DENSHAM SURGERY
1  A81002  QUEENS PARK MEDICAL CENTRE
2  A81003   VICTORIA MEDICAL PRACTICE
3  A81004     BLUEBELL MEDICAL CENTRE
4  A81005          SPRINGWOOD SURGERY

In [92]:
opioid_scores.to_frame() #converting series to dataframe

               0
A81005 -0.548306
A81007  1.544557
A81011  2.291795
A81012  1.373060
A81017  0.583168
...          ...
Y05570  1.391142
Y05583 -1.019657
Y05597 -0.817544
Y05660 -1.278102
Y05670 -0.667522

[856 rows x 1 columns]

In [93]:
# renaming the column
opioid_scores.to_frame().rename(columns={0: 'z-score'})

         z-score
A81005 -0.548306
A81007  1.544557
A81011  2.291795
A81012  1.373060
A81017  0.583168
...          ...
Y05570  1.391142
Y05583 -1.019657
Y05597 -0.817544
Y05660 -1.278102
Y05670 -0.667522

[856 rows x 1 columns]

In [94]:
#D1
unique_practices_by_name.merge(opioid_scores.to_frame().rename(columns={0: 'z-score'}), left_on='code',right_index=True)

         code                                 name   z-score
4      A81005                   SPRINGWOOD SURGERY -0.548306
6      A81007                    BANKHOUSE SURGERY  1.544557
9      A81011                    CHADWICK PRACTICE  2.291795
10     A81012            WESTBOURNE MEDICAL CENTRE  1.373060
15     A81017                  WOODBRIDGE PRACTICE  0.583168
...       ...                                  ...       ...
10702  Y05570         OLDHAM 7 DAY ACCESS HUB3 OOH  1.391142
10713  Y05583                   CYPS - ACORN HOUSE -1.019657
10725  Y05597  WORKING AGE ADULTS - ST OWEN STREET -0.817544
10769  Y05660       BRENT GP ACCESS WALK-IN CENTRE -1.278102
10777  Y05670     SUNDERLAND NORTH EXTENDED ACCESS -0.667522

[856 rows x 3 columns]

In [95]:
scripts['practice'].value_counts().to_frame()

        practice
N83028      2844
L83100      2797
D81043      2459
B81008      2396
B81026      2347
...          ...
C85617         1
Y03010         1
Y01174         1
Y03179         1
Y03472         1

[856 rows x 1 columns]

In [96]:
#D2
scripts['practice'].value_counts().to_frame().rename(columns={'practice':'count'})

        count
N83028   2844
L83100   2797
D81043   2459
B81008   2396
B81026   2347
...       ...
C85617      1
Y03010      1
Y01174      1
Y03179      1
Y03472      1

[856 rows x 1 columns]

In [97]:
#merging D1 & D2
joined = unique_practices_by_name\
.merge(opioid_scores.to_frame()\
.rename(columns={0: 'z-score'}), left_on='code',right_index=True)\
.merge(scripts['practice'].value_counts().to_frame().rename(columns={'practice':'count'}),left_on='code',right_index=True)

In [98]:
joined

         code                                 name   z-score  count
4      A81005                   SPRINGWOOD SURGERY -0.548306   1507
6      A81007                    BANKHOUSE SURGERY  1.544557   1454
9      A81011                    CHADWICK PRACTICE  2.291795   1568
10     A81012            WESTBOURNE MEDICAL CENTRE  1.373060   1332
15     A81017                  WOODBRIDGE PRACTICE  0.583168   2150
...       ...                                  ...       ...    ...
10702  Y05570         OLDHAM 7 DAY ACCESS HUB3 OOH  1.391142     22
10713  Y05583                   CYPS - ACORN HOUSE -1.019657     28
10725  Y05597  WORKING AGE ADULTS - ST OWEN STREET -0.817544     18
10769  Y05660       BRENT GP ACCESS WALK-IN CENTRE -1.278102    347
10777  Y05670     SUNDERLAND NORTH EXTENDED ACCESS -0.667522     12

[856 rows x 4 columns]

In [99]:
joined.sort_values('z-score',ascending=False)

         code                                name    z-score  count
8096   Y01852           NATIONAL ENHANCED SERVICE  11.695818      7
8679   Y03006            OUTREACH SERVICE NH / RH   7.339043      2
9089   Y03668     BRISDOC HEALTHCARE SERVICES OOH   6.150582     60
3455   G81703              H&R P C SPECIAL SCHEME   5.123032     36
10215  Y04997                      HMR BARDOC OOH   4.958866    321
...       ...                                 ...        ...    ...
2378   E85030            CHISWICK HEALTH PRACTICE  -3.677861   1150
9881   Y04606          LANCASTER HOUSE CONTINENCE  -4.060379    444
10607  Y05431  NOTTS APPLIANCE MANAGEMENT SERVICE  -4.256817    488
10606  Y05430  NOTTS APPLIANCE MANAGEMENT SERVICE  -4.334613    506
6100   M85715       SOHO ROAD PRIMARY CARE CENTRE  -4.480561   1401

[856 rows x 4 columns]

In [100]:
[i[1:] for i in joined.sort_values('z-score',ascending=False).itertuples()]

[('Y01852', 'NATIONAL ENHANCED SERVICE', 11.695817862936027, 7),
 ('Y03006', 'OUTREACH SERVICE NH / RH', 7.339043019238823, 2),
 ('Y03668', 'BRISDOC HEALTHCARE SERVICES OOH', 6.1505817490838295, 60),
 ('G81703', 'H&R P C SPECIAL SCHEME', 5.123032414033079, 36),
 ('Y04997', 'HMR BARDOC OOH', 4.958866438487605, 321),
 ('Y04585', 'INTEGRATED CARE 24 LTD (CWSX OOH)', 4.8888781604828235, 426),
 ('P81051', 'DARWEN HEALTHCARE', 4.83915896863634, 1917),
 ('P87017', 'THE LIMES MEDICAL PRACTICE', 4.546841872334426, 1321),
 ('Y01086', 'IC24 LTD (BRIGHTON & HOVE OOH)', 4.335047010605196, 357),
 ('Y05327', 'OLDHAM 7 DAY ACCESS HUB2 OOH', 4.31178403661019, 56),
 ('Y00502', 'IC24 LTD (NORFOLK & WISBECH OOH)', 4.2575005924727645, 489),
 ('Y04657', 'ROSSENDALE MIU & OOH', 4.256827446322491, 18),
 ('Y00016', 'BURY WALK-IN CENTRE', 4.150589122881537, 138),
 ('Y04587', 'IC24 LTD (HORSHAM & MID SUSSEX OOH)', 3.7816207038443523, 215),
 ('Y04921', 'LCW HOUNSLOW CCG OOH', 3.582848546206269, 69),
 ('Y05419', 'WEEKEND WORKING EASINGTON NORTH', 3.565938771129765, 278),
 ('Y02947', 'COMPASS ENFIELD', 3.5587202651067935, 7),
 ('Y00581', 'BASSETLAW DRUG & ALCOHOL SERVICE', 3.5332641025115423, 2),
 ('A88603', 'THE PARK SURGERY', 3.511114736389202, 969),
 ('G81061', 'CHAPEL STREET SURGERY', 3.4907459502707447, 1504),
 ('L81087', 'BEECHWOOD MEDICAL PRACTICE', 3.4747953064338977, 1552),
 ('Y01696', 'BASSETLAW HOSPICE OF THE GOOD SHEPHERD', 3.454423428527398, 46),
 ('G81014', 'CARDEN SURGERY', 3.4503113243413193, 1375),
 ('Y01716', 'GP IN A&E (WIC)', 3.3959177486386096, 87),
 ('Y00234', 'NORTHAMPTONSHIRE OOH SERVICE', 3.39355927807245, 382),
 ('P81057', 'WORDEN MEDICAL CENTRE', 3.341328344384246, 1898),
 ('Y03662', 'BRISDOC HEALTHCARE SERVICES OOH', 3.333643839656514, 566),
 ('Y01003', 'BURY OOH', 3.3215295599703474, 292),
 ('Y00860', 'IC24 SOUTHEND/CP&R CCG OOH', 3.2211153199464, 336),
 ('Y04586', 'IC24 LTD (CRAWLEY OOH)', 3.1942640976202856, 173),
 ('Y03787', 'EASTBOURNE  HAILSHAM & SEAFORD OOH', 2.9896925335154507, 255),
 ('A81610', 'THE ROSEBERRY PRACTICE', 2.9803589486570257, 1450),
 ('B86016', 'SHAFTESBURY MEDICAL CTR.', 2.904593003935284, 2126),
 ('P81025', 'THE RICHMOND HILL PRACTICE', 2.860189197858325, 1729),
 ('Y04426', 'DGS OOH (INTEGRATED CARE 24 LTD)', 2.795651191074179, 325),
 ('C86016', 'THE LAKESIDE PRACTICE', 2.7801243484267157, 1554),
 ('Y01943', 'DEWSBURY MSK SERVICE', 2.773644352185692, 3),
 ('Y03703', 'BRISDOC HEALTHCARE SERVICES OOH', 2.7220204978636375, 74),
 ('P82022', 'HALLIWELL SURGERY 1', 2.6902312553464682, 1124),
 ('P85013', 'THE ROYTON & CROMPTON FAMILY PRACTICE', 2.667409950287062, 2054),
 ('B81069',
  'PRACTICE 3  MEDICAL CENTRE  BRIDLINGTON',
  2.6526642039852844,
  1936),
 ('Y05493', 'LCWUCC - IUC NCL', 2.5927932420214392, 443),
 ('P84032', 'DR MOKASHI', 2.496887689055938, 1341),
 ('L81095', 'THE CREST FAMILY PRACTICE', 2.494358442548829, 1294),
 ('P85608', 'PERKINS PRACTICE', 2.479571342887134, 899),
 ('M91025', 'DARLASTON HEALTH CENTRE', 2.4456345065842657, 996),
 ('Y00469', "DR MA SIMS' PRACTICE", 2.437276610645611, 1857),
 ('P87652', '1/LOWER BROUGHTON MEDICAL PRACTICE', 2.435636753514273, 1044),
 ('G81013', 'CORNWALLIS PLAZA SURGERY', 2.424202462055629, 2326),
 ('Y02606', 'FAIRMORE MEDICAL PRACTICE', 2.3824085989710504, 1288),
 ('M82619', 'LAWLEY MEDICAL PRACTICE', 2.373577973078906, 1409),
 ('P83021', "PEEL GP'S", 2.353594338493154, 1557),
 ('P84051', 'EASTLANDS MEDICAL CENTRE', 2.325396683274206, 1369),
 ('N84010', 'MAGHULL HEALTH CENTRE (DR SAPRE)', 2.3194074094375097, 1322),
 ('Y00390', 'INTEGRATED CARE 24 LIMITED OOH', 2.3106497615538943, 511),
 ('Y02521', 'WILLOW BANK SURGERY', 2.295642132037915, 1934),
 ('Y03819', 'IC24 LTD (HWLH OOH)', 2.2949004338925127, 216),
 ('A81011', 'CHADWICK PRACTICE', 2.2917945205697303, 1568),
 ('M86639', 'C&WPT OOH SERVICE', 2.2708524012737876, 341),
 ('L81094', 'THE MERRYWOOD PRACTICE', 2.2705509556396586, 1234),
 ('Y03656', 'LEYLAND SURGERY', 2.251774286539937, 1213),
 ('P87008', 'WALKDEN MEDICAL PRACTICE', 2.2415736140706994, 1577),
 ('P83007', 'RADCLIFFE MEDICAL PRACTICE', 2.2396070334595315, 1553),
 ('P83005', 'RIBBLESDALE GP-DR SUBBIAH', 2.2097458912614827, 1100),
 ('P84637', 'THE MAZHARI & KHAN PRACTICE', 2.2006627122644895, 912),
 ('B81112', 'JAMES ALEXANDER FAMILY PRACTICE', 2.1967025909056024, 1634),
 ('Y01838', 'B&H INTERMEDIATE CARE SERVICE', 2.1862131918267544, 456),
 ('M91022', 'HARDEN SURGERY', 2.155495816284959, 1228),
 ('G82044', 'THE GATEWAY MEDICAL PRACTICE', 2.154423496545371, 1349),
 ('P85026', 'QUAYSIDE MEDICAL PRACTICE', 2.1535448371359025, 1422),
 ('Y00599', 'HASTINGS AND ROTHER OOH', 2.076490970994684, 291),
 ('L81013', 'FISHPONDS FAMILY PRACTICE', 2.0743592136603786, 1632),
 ('A89019', 'DRS CLOAK  CHOI AND MILLIGAN', 2.0511156727220916, 1661),
 ('M91612', "ST MARY'S SURGERY", 2.041026500575296, 981),
 ('P81079', 'THE THORNTON PRACTICE', 1.9970130183083867, 1970),
 ('Y04588', 'IC24 LTD (EAST SURREY OOH)', 1.9530599800408153, 194),
 ('P84043', 'CORNISHWAY GROUP PRACTICE', 1.9529030654485127, 1506),
 ('P92621', 'PREMIER HEALTH TEAM', 1.9342677920567377, 876),
 ('A89022', 'CONCORD MEDICAL PRACTICE', 1.9339605744520654, 1386),
 ('A81058', 'COULBY MEDICAL PRACTICE', 1.9268085445885355, 1585),
 ('C84064', 'PARKSIDE MEDICAL CENTRE', 1.9235518278308144, 1314),
 ('A81064', 'THE DISCOVERY PRACTICE', 1.9047661015943373, 1268),
 ('B81026', 'ANCORA MEDICAL PRACTICE', 1.8854159223309173, 2347),
 ('P81140', 'DARWEN HEALTHLINK', 1.8822754121466374, 2019),
 ('P85601', 'JALAL PRACTICE', 1.8661104279692895, 885),
 ('B83042', 'ROOLEY LANE MED. CENTRE', 1.8635817801511316, 1522),
 ('N82669', 'GREAT HOMER STREET MEDICAL CENTRE', 1.813002119840964, 1062),
 ('Y02344', 'NORTHPOINT', 1.8024326949572382, 1137),
 ('P81092', 'THE CRESCENT SURGERY', 1.7989165864147443, 1734),
 ('N81096', 'BROOKVALE PRACTICE', 1.7979440966591638, 1484),
 ('Y00675', 'LEIGH NHS WIC', 1.7760099128664424, 162),
 ('B87006', 'DR SP SINGH AND PARTNERS', 1.772041643578181, 1840),
 ('B82092', 'BELGRAVE SURGERY', 1.7643723369327995, 1291),
 ('P85006', 'THE PARKS MEDICAL PRACTICE', 1.7589687048174796, 1466),
 ('F81106', 'THE ROSS PRACTICE', 1.7231557395207378, 1648),
 ('D81024', 'THOMAS WALKER', 1.69692378556541, 1377),
 ('A81033', 'OAKFIELD MEDICAL PRACTICE', 1.6948316951338191, 1055),
 ('P81684', "DR DP CHARLES' PRACTICE", 1.691315520903282, 1353),
 ('N81121', 'NORTHGATE VILLAGE SURGERY', 1.6861842319656928, 1304),
 ('P81099', 'DR THM MACKENZIE & PARTNERS', 1.682911604319903, 1782),
 ('P92021', "DR D'ARIFAT & PTNRS", 1.6637923954926253, 1483),
 ('P81125', "DR IJ MOODIE'S PRACTICE", 1.6563720750281563, 1686),
 ('Y04168', 'EAST KENT OOH', 1.638493758833619, 51),
 ('P84029', 'BENCHILL MEDICAL PRACTICE', 1.6339779607285454, 1741),
 ('B82001', 'FALSGRAVE SURGERY', 1.61171969956088, 1720),
 ('P81668', 'FLEETWOOD SURGERY', 1.6024886028908925, 1243),
 ('P85010', 'WOODLANDS MEDICAL PRACTICE', 1.601496189601277, 1722),
 ('P81086', 'BROADWAY MEDICAL CENTRE', 1.6005432595061824, 1773),
 ('Y01124', 'THE DURU PRACTICE', 1.5987699004806988, 1119),
 ('C86018', 'NORTHFIELD SURGERY', 1.5883138172000437, 1750),
 ('H81615', 'FARNHAM DENE MEDICAL PRACTICE', 1.5820860464143955, 1675),
 ('N81107', 'MANCHESTER ROAD SURGERY', 1.5704546458844995, 827),
 ('P81073', 'CLEVELEYS GROUP PRACTICE', 1.5556434570674689, 1731),
 ('A89604', 'DR WEATHERHEAD & ASSOCIATES', 1.5532763602842234, 1151),
 ('B83041', 'BOWLING HALL MED PRACTICE', 1.5508054491180876, 1352),
 ('B81119', 'DR G PALOORAN AND PARTNERS', 1.5469880916541456, 1202),
 ('A81007', 'BANKHOUSE SURGERY', 1.5445572938670182, 1454),
 ('P83015', 'RIBBLESDALE MEDICAL PRACTICE', 1.5422881585838142, 1278),
 ('A89010', 'DR STEPHENSON & PARTNERS', 1.5384470725000152, 1658),
 ('Y03079', 'BOLTON COMMUNITY PRACTICE', 1.525301453698154, 2147),
 ('P92647', 'OLLERTON A', 1.5088262107405006, 1083),
 ('D83021', 'HAVERHILL FAMILY PRACTICE', 1.500958686487295, 1921),
 ('N81023',
  'WHITBY GROUP PRACTICE SURGERY   (GREEN)',
  1.4895692064235049,
  1136),
 ('C87622', 'GATEWAY PRIMARY CARE', 1.488910940697685, 1464),
 ('P82001', 'THE DUNSTAN PARTNERSHIP', 1.4768681168750906, 1721),
 ('C83082', 'BIRCHWOOD MEDICAL PRACTICE', 1.472721678222517, 1773),
 ('F81047', 'THE HAMILTON PRACTICE', 1.4602751797056142, 1571),
 ('L83118', 'CHELSTON HALL SURGERY', 1.4460886347963144, 1804),
 ('C86614', 'THORNE MOOR MEDICAL PRACTICE', 1.4428242172226475, 1779),
 ('N81050', 'THE GREAT SUTTON MED.CTR. (GREEN)', 1.4286810856399208, 1424),
 ('Y03640', 'DMC SHEPPEY-W.I. CLINIC', 1.4268407280657627, 202),
 ('P89008', 'BEDFORD HOUSE MEDICAL CENTRE', 1.4253374356608446, 1501),
 ('Y04531', 'WOODSIDE GROUP PRACTICE-CICS', 1.422651783603667, 116),
 ('P85008', 'FAILSWORTH GROUP PRACTICE', 1.4226313605776026, 1989),
 ('G82020', 'THE GRANGE PRACTICE', 1.4109225755192847, 2069),
 ('Y02755', 'ROCK HEALTHCARE LIMITED', 1.4095600358501912, 1275),
 ('P84020', 'PEEL HALL MEDICAL CENTRE', 1.393463701246733, 1558),
 ('Y05570', 'OLDHAM 7 DAY ACCESS HUB3 OOH', 1.3911416481292795, 22),
 ('N81111', 'MEREPARK MEDICAL CENTRE', 1.3904665496542028, 1329),
 ('C84103', 'THE FOREST PRACTICE', 1.3875521291326736, 1228),
 ('F81151', 'MALLING HEALTH - DIPPLE MEDICAL CENTRE', 1.381490845899131, 1229),
 ('A81012', 'WESTBOURNE MEDICAL CENTRE', 1.3730602244461536, 1332),
 ('N81089', 'GREENBANK SURGERY', 1.3651181382860496, 1666),
 ('N83020', 'BREACH & PARTNERS', 1.3615359175513242, 1641),
 ('A88011', 'WESTOE SURGERY', 1.3594461647943423, 905),
 ('Y05269', 'URGENT CARE CENTRE', 1.3578598299321634, 8),
 ('B81113', 'CEDAR MEDICAL PRACTICE', 1.3569642493283887, 1488),
 ('C86605', 'ASKERN MEDICAL PRACTICE', 1.3548242186109558, 1514),
 ('N82099', 'MERE LANE GROUP PRACTICE', 1.350944309861578, 1566),
 ('N81054', 'WEAVER VALE PRACTICE', 1.350944309861578, 1566),
 ('Y05107', 'STAR SCHEME', 1.3502561206962944, 298),
 ('L81033', 'NIGHTINGALE VALLEY PRACTICE', 1.3491921646463492, 1592),
 ('N81102', 'FOUNTAINS MEDICAL PRACTICE', 1.317413083116083, 936),
 ('P83020', 'MINDEN FAMILY PRACTICES - DR SAXENA', 1.306348689880963, 1216),
 ('Y02322', 'LEIGH FAMILY PRACTICE', 1.3048443710022197, 1652),
 ('P89015', 'MILLGATE HEALTHCARE PARTNERSHIP', 1.2971966660492111, 2016),
 ('Y00050', 'GUPTA K', 1.2951818031871445, 739),
 ('C83072', 'MINSTER MEDICAL PRACTICE', 1.288514909007341, 1681),
 ('G82791', 'DR S CHANDRAN PRACTICE', 1.2883403565367995, 1270),
 ('N81093', 'WHITBY GROUP PRACTICE SURGERY   (RED)', 1.285205415886258, 1245),
 ('P89020', 'HT PRACTICE', 1.2811881137599088, 1605),
 ('P81123', 'ELMS FEDERATED PRACTICE', 1.2802773366140776, 2202),
 ('P81074', 'HIGHFIELD SURGERY', 1.269462180886422, 1944),
 ('N81047', 'THE KILTEARN MEDICAL CTR.', 1.2647664643222594, 1945),
 ('N81095', 'THE GREAT SUTTON MED.CTR. (BLUE)', 1.2543952450137712, 1404),
 ('L84056', 'THE CORINTHIAN SURGERY', 1.241718704113957, 1432),
 ('A89025', 'ENCOMPASS HEALTH CARE', 1.2412876016949501, 1820),
 ('B81008', 'EAST HULL FAMILY PRACTICE', 1.233319051803214, 2396),
 ('C84013', 'BRIDGEGATE AND TALL TREES PARTNERSHIP', 1.2196876535213519, 2242),
 ('C83047', 'WESTSIDE SURGERY', 1.2129163477708735, 1670),
 ('P87654', '3/LOWER BROUGHTON MEDICAL PRACTICE', 1.2125457464520104, 1360),
 ('P84014', 'RK MEDICAL PRACTICE', 1.2122585554404182, 1206),
 ('A81031', 'HAVELOCK GRANGE PRACTICE', 1.2075826887040852, 1697),
 ('M83023', 'KIDSGROVE MEDICAL CENTRE', 1.1986824798679596, 1595),
 ('P92035', 'LILFORD PARK SURGERY', 1.198198148736751, 1004),
 ('L81051', 'NEW COURT SURGERY', 1.197893470510659, 1855),
 ('M86021', 'SPRINGFIELD MEDICAL PRACTICE', 1.1966900982629167, 1466),
 ('Y00459', 'COMMUNITY CARE (SW)', 1.1925307052169503, 310),
 ('C87017', 'CLIFTON MEDICAL CENTRE', 1.1724230596897316, 1704),
 ('B81688', "DR KV GOPAL'S PRACTICE", 1.1720953754395058, 805),
 ('P82025', 'BURNSIDE SURGERY', 1.168941124406708, 1085),
 ('Y02660', 'THE RLC SURGERY', 1.1495569546254027, 884),
 ('P81020', 'ST. NICHOLAS GROUP PRACTICE', 1.1468782291168675, 1631),
 ('N83022', 'LIME GROVE SURGERY', 1.133324345723406, 1764),
 ('Y02506', 'SHEPPEY NHS HEALTHCARE CENTRE', 1.1055703705604765, 1379),
 ('P87659', '3/ST ANDREWS MEDICAL CENTRE', 1.1030414100257449, 1044),
 ('M83075', 'NORFOLK STREET SURGERY', 1.1001086284135098, 1588),
 ('N83060', 'HOLLY BANK SURGERY', 1.0964446098374663, 1277),
 ('Y04913', 'BURY GP PRACTICES LTD', 1.0845664864263769, 367),
 ('N82048', 'WALTON MEDICAL CENTRE', 1.0837804858779618, 1539),
 ('Y05095', 'CHOICE PLUS', 1.0784871303055021, 319),
 ('N85639', 'GP OOH VCH', 1.0703202855828937, 27),
 ('P81032', 'REEDYFORD HLTH CARE GROUP', 1.06223626051814, 1831),
 ('B87031', 'CHURCH STREET SURGERY', 1.0430843190878876, 1835),
 ('P88625', 'ARCHWOOD MEDICAL PRACTICE', 1.0245197687687233, 1498),
 ('N82097', 'THE GREY ROAD SURGERY', 1.0038433436263696, 624),
 ('Y04920', 'LCW CLCCG OOH', 0.990960654816569, 182),
 ('P82002', 'PIKES LANE 1', 0.9825683223467009, 1716),
 ('Y00758', "DR JO ARAYOMI'S PRACTICE", 0.9809621870817135, 754),
 ('Y00984', 'ROCHFORD MEDICAL CENTRE', 0.9799631856562926, 1454),
 ('B85012', 'UNDERCLIFFE SURGERY', 0.9698341933006762, 1824),
 ('M91033', 'WILLENHALL MEDICAL CENTRE', 0.962167292159505, 1040),
 ('L81043', 'LONGTON GROVE SURGERY', 0.9596568604516538, 1484),
 ('Y04923', 'LCW WLCCG OOH', 0.957148650663613, 184),
 ('L81120', 'BIRCHWOOD MEDICAL PRACTICE', 0.9561493228499358, 1406),
 ('A89003', 'DR AKK HEGDE', 0.9558045471392788, 1197),
 ('N81024', 'SWANLOW MEDICAL CENTRE', 0.9512357747269645, 1696),
 ('C85022', 'HOYLAND MEDICAL PRACTICE', 0.9511674525152329, 2013),
 ('A85009', 'CROWHALL MEDICAL CENTRE', 0.9475546812187514, 1329),
 ('N83026', 'PARKFIELD SURGERY', 0.9474848385914434, 887),
 ('A85011', 'ST. ALBANS MEDICAL GROUP', 0.9429444643120889, 1356),
 ('B81002',
  'DR AK CHOUDHARY & DR SR DANDA PRACTICE',
  0.9427251507046625,
  1069),
 ('Y05233', 'ASHTON PCC SEVEN DAY ACCESS OOH', 0.9302812647048243, 162),
 ('F81164', 'WEST ROAD SURGERY', 0.9295334512018925, 1674),
 ('L83008', 'PATHFIELDS PRACTICE', 0.9240621160505019, 1913),
 ('P83603', 'RED BANK GROUP PRACTICE', 0.9227449971049798, 1781),
 ('N84025', 'WESTWAY MEDICAL CENTRE', 0.9226455564901442, 1649),
 ('M83046', 'BIDDULPH VALLEY SURGERY', 0.9196339826731841, 1861),
 ('Y05540', 'PRIMARY CARE ACCESS HUB (SOUTH STOKE)', 0.9073821069008918, 94),
 ('M83100', 'DR P D MILES AND DR R VALASAPALLI', 0.8963715748018126, 1207),
 ('B81081', 'NEW GREEN SURGERY', 0.886663431249655, 1104),
 ('Y01262', 'PALLION PRIMARY CARE SERVICES', 0.8848372301316297, 51),
 ('N81127', 'THE WEAVER VALE SURGERY', 0.8699041432770583, 1686),
 ('M83629', 'DRAYTON ROAD SURGERY', 0.8642134853846423, 1160),
 ('N83023', 'PARK HOUSE SURGERY', 0.8583539465845199, 1556),
 ('P83019', 'MINDEN FAMILY PRACTICES - DR NORMAN', 0.8521636161961919, 1162),
 ('A81065', 'THE ESTON SURGERY', 0.8473111608324938, 1058),
 ('Y02869', 'LCW EALING CCG OOH', 0.8450218984095034, 74),
 ('C83009', 'LINDUM MEDICAL PRACTICE', 0.837099417189567, 1852),
 ('P88019', 'ALVANLEY FAMILY PRACTICE', 0.8298228987797709, 1192),
 ('N81029', 'SOUTH PARK SURGERY', 0.8267941297318386, 1801),
 ('N83028', 'ASTON HEALTHCARE LIMITED', 0.8252478804686255, 2844),
 ('C83038', 'THE GLEBE PRACTICE', 0.8248605688052394, 1828),
 ('P92642', 'MARUS BRIDGE PRACTICE', 0.8237943459021226, 1272),
 ('L82001', 'LANDER MEDICAL PRACTICE', 0.8237510565288222, 1988),
 ('M91028', 'BERKLEY PRACTICE', 0.8140128744254036, 1221),
 ('B85030', 'SCRIVINGS CLECKHEATON HLTH CTR', 0.8018549254355714, 1753),
 ('G81016', 'QUAYSIDE MEDICAL PRACTICE', 0.787173293679104, 1623),
 ('C83041', 'THE WOODLAND MEDICAL PRACTICE', 0.7855827587488712, 1464),
 ('B86054', 'THE GARDEN SURGERY', 0.7831558146326651, 1677),
 ('P89033', 'TAME VALLEY MEDICAL CENTRE', 0.7806906147170479, 1518),
 ('P83008', 'DR S DE VIAL & PARTNERS', 0.7781275780654585, 1280),
 ('N81016', 'MILLCROFT MEDICAL CENTRE', 0.7776664291479318, 1838),
 ('Y03077', 'ST CHARLES UCC CENTRE WIC', 0.7705083359699624, 220),
 ('A81037', 'THE ERIMUS PRACTICE', 0.7696858936929334, 1467),
 ('E82656', 'CASSIO SURGERY - E82656', 0.7682017553313284, 549),
 ('A81049', 'KINGS MEDICAL CENTRE', 0.7636990655837835, 1362),
 ('L83032', 'BARTON HEALTH CENTRE', 0.7617056437539289, 1708),
 ('P84037', 'DR CUNNINGHAM & PARTNERS', 0.7610780708855999, 1283),
 ('N81091',
  'WHITBY GROUP PRACTICE SURGERY   (BLACK)',
  0.7600614005610314,
  1151),
 ('P88025', 'HULME HALL MEDICAL GROUP', 0.7568214917305293, 1709),
 ('D81043', 'GRANTA MEDICAL PRACTICES', 0.7555287950195516, 2459),
 ('M81005', 'NORTHUMBERLAND HOUSE SURGERY', 0.7519402615343426, 1710),
 ('C84136', "ST. LUKE'S SURGERY", 0.723660445288471, 867),
 ('N81013', 'HIGH STREET SURGERY', 0.72219436205385, 1476),
 ('E82083', 'THE COLNE PRACTICE', 0.7186406047695717, 1610),
 ('A81040', 'MARSH HOUSE MEDICAL PRACTICE', 0.7169358342643549, 1477),
 ('N81066', 'GROVE HOUSE PRACTICE', 0.7130829482184741, 1825),
 ('P81072', 'GLENROYD MEDICAL CENTRE', 0.7122077997071193, 2147),
 ('C81023', 'THE AITUNE MEDICAL PRACTICE', 0.7116809476785296, 1478),
 ('N85034', 'PARKFIELD MED CTR', 0.7064296967141186, 1479),
 ('B81014', 'PRACTICE TWO', 0.6985635919516416, 1614),
 ('Y05401', 'WLCCG EXTENDED HOURS HUBS', 0.698070268947408, 151),
 ('F81724', 'DR GUL  NEW WESTBOROUGH SURGERY', 0.696279600867936, 950),
 ('F81128', 'EASTWOOD GROUP PRACTICE', 0.6867125295107185, 1777),
 ('P81006', 'WINDSOR SURGERY', 0.6867125295107185, 1777),
 ('N81040', 'HIGH STREET PRACTICE WINSFORD', 0.6842294387761383, 1270),
 ('E85700', 'MANOR HOUSE PRACTICE', 0.6799018576368129, 585),
 ('G81036', 'WARMDENE SURGERY', 0.6747308785251107, 1592),
 ('B87036', 'DR DP DIGGLE & DR RE PHILLIPS', 0.673932120228703, 1192),
 ('B85014', 'BROOKROYD HOUSE', 0.6727407681715113, 1941),
 ('P88007', 'CHEADLE HULME HEALTH CTR 2', 0.6708345941289015, 1834),
 ('H83027', 'PARKWAY HEALTH CENTRE (01)', 0.6670921650502024, 1140),
 ('P81133', 'THE VILLAGE PRACTICE', 0.6654780823049627, 1701),
 ('P81069', 'PENDLESIDE MEDICAL PRACT', 0.6621757817801986, 1809),
 ('M83084', 'DR ROBINSON & PARTNERS', 0.6568399547279616, 1435),
 ('M81047', 'SPA MEDICAL PRACTICE', 0.6556710319844413, 1569),
 ('P82018', 'THE ALASTAIR ROSS MEDICAL PRACTICE', 0.6484485323889041, 1303),
 ('P92653', 'DALTON TM', 0.6438067441715126, 905),
 ('H81054', 'BRIDGE PRACTICE', 0.6412261496745635, 1331),
 ('D83012',
  'CLEMENTS AND CHRISTMAS MALTINGS SURGERY',
  0.6303462989019086,
  2193),
 ('M91034', 'BLOXWICH MEDICAL PRACTICE', 0.6293506643313972, 1253),
 ('G81042', 'BEACONSFIELD MEDICAL PRACTICE', 0.6280934491900776, 1494),
 ('P88009', 'WOODLEY VILLAGE SURGERY', 0.6269977523475423, 881),
 ('M85766', 'BALSALL HEATH HEALTH CENTRE (S)', 0.6237354652199553, 855),
 ('N81085', 'PARK LANE SURGERY', 0.622899619167999, 1495),
 ('N81062', 'CUMBERLAND HOUSE SURGERY', 0.622126144993372, 2060),
 ('M81034', 'SALTERS MEDICAL PRACTICE', 0.6194697614744834, 1603),
 ('N81053', 'EARNSWOOD MEDICAL CENTRE', 0.6181466918916494, 1980),
 ('L84008', "ST.GEORGE'S SURGERY", 0.614434802765777, 1443),
 ('C88043', 'TRAMWAYS 54A MC', 0.6134440381422872, 1470),
 ('M91010', 'PORTLAND MEDICAL PRACTICE', 0.6112129326227975, 1766),
 ('M81066', 'WARGRAVE HOUSE SURGERY', 0.6057857821161828, 1552),
 ('P81159', 'STONYHILL MEDICAL PRACTICE', 0.5994706242530964, 1607),
 ('C85001',
  'GOLDTHORPE MEDICAL CENTRE PMS PRACTICE',
  0.5939841531317112,
  1286),
 ('F81158', 'DR NASAH & PARTNERS', 0.5845873602998019, 1047),
 ('A81017', 'WOODBRIDGE PRACTICE', 0.5831681324607861, 2150),
 ('P81002', 'DALTON SQUARE PRACTICE', 0.5641629836538311, 1668),
 ('M83089', 'BIDDULPH DOCTORS', 0.5638966694062103, 1884),
 ('M86005', 'HILLFIELDS HEALTH CENTRE - 1', 0.561764324157037, 1453),
 ('M81094', 'ABBEY MEDICAL PRACTICE', 0.5596240025202572, 1615),
 ('Y02274', 'INTRAHEALTH PLATT BRIDGE', 0.5488445732594632, 1026),
 ('N83622', 'PRIMROSE MEDICAL PRACTICE', 0.5405084225645144, 734),
 ('Y00151', 'COLLINGWOOD MEDICAL GROUP', 0.5397498025838636, 1081),
 ('A81021', 'NORMANBY MEDICAL CENTRE', 0.5367118450072036, 1917),

In [101]:
anomalies = [i[1:] for i in joined.sort_values('z-score',ascending=False).itertuples()][:100]

In [102]:
anomalies

[('Y01852', 'NATIONAL ENHANCED SERVICE', 11.695817862936027, 7),
 ('Y03006', 'OUTREACH SERVICE NH / RH', 7.339043019238823, 2),
 ('Y03668', 'BRISDOC HEALTHCARE SERVICES OOH', 6.1505817490838295, 60),
 ('G81703', 'H&R P C SPECIAL SCHEME', 5.123032414033079, 36),
 ('Y04997', 'HMR BARDOC OOH', 4.958866438487605, 321),
 ('Y04585', 'INTEGRATED CARE 24 LTD (CWSX OOH)', 4.8888781604828235, 426),
 ('P81051', 'DARWEN HEALTHCARE', 4.83915896863634, 1917),
 ('P87017', 'THE LIMES MEDICAL PRACTICE', 4.546841872334426, 1321),
 ('Y01086', 'IC24 LTD (BRIGHTON & HOVE OOH)', 4.335047010605196, 357),
 ('Y05327', 'OLDHAM 7 DAY ACCESS HUB2 OOH', 4.31178403661019, 56),
 ('Y00502', 'IC24 LTD (NORFOLK & WISBECH OOH)', 4.2575005924727645, 489),
 ('Y04657', 'ROSSENDALE MIU & OOH', 4.256827446322491, 18),
 ('Y00016', 'BURY WALK-IN CENTRE', 4.150589122881537, 138),
 ('Y04587', 'IC24 LTD (HORSHAM & MID SUSSEX OOH)', 3.7816207038443523, 215),
 ('Y04921', 'LCW HOUNSLOW CCG OOH', 3.582848546206269, 69),
 ('Y05419', 'WEEKEND WORKING EASINGTON NORTH', 3.565938771129765, 278),
 ('Y02947', 'COMPASS ENFIELD', 3.5587202651067935, 7),
 ('Y00581', 'BASSETLAW DRUG & ALCOHOL SERVICE', 3.5332641025115423, 2),
 ('A88603', 'THE PARK SURGERY', 3.511114736389202, 969),
 ('G81061', 'CHAPEL STREET SURGERY', 3.4907459502707447, 1504),
 ('L81087', 'BEECHWOOD MEDICAL PRACTICE', 3.4747953064338977, 1552),
 ('Y01696', 'BASSETLAW HOSPICE OF THE GOOD SHEPHERD', 3.454423428527398, 46),
 ('G81014', 'CARDEN SURGERY', 3.4503113243413193, 1375),
 ('Y01716', 'GP IN A&E (WIC)', 3.3959177486386096, 87),
 ('Y00234', 'NORTHAMPTONSHIRE OOH SERVICE', 3.39355927807245, 382),
 ('P81057', 'WORDEN MEDICAL CENTRE', 3.341328344384246, 1898),
 ('Y03662', 'BRISDOC HEALTHCARE SERVICES OOH', 3.333643839656514, 566),
 ('Y01003', 'BURY OOH', 3.3215295599703474, 292),
 ('Y00860', 'IC24 SOUTHEND/CP&R CCG OOH', 3.2211153199464, 336),
 ('Y04586', 'IC24 LTD (CRAWLEY OOH)', 3.1942640976202856, 173),
 ('Y03787', 'EASTBOURNE  HAILSHAM & SEAFORD OOH', 2.9896925335154507, 255),
 ('A81610', 'THE ROSEBERRY PRACTICE', 2.9803589486570257, 1450),
 ('B86016', 'SHAFTESBURY MEDICAL CTR.', 2.904593003935284, 2126),
 ('P81025', 'THE RICHMOND HILL PRACTICE', 2.860189197858325, 1729),
 ('Y04426', 'DGS OOH (INTEGRATED CARE 24 LTD)', 2.795651191074179, 325),
 ('C86016', 'THE LAKESIDE PRACTICE', 2.7801243484267157, 1554),
 ('Y01943', 'DEWSBURY MSK SERVICE', 2.773644352185692, 3),
 ('Y03703', 'BRISDOC HEALTHCARE SERVICES OOH', 2.7220204978636375, 74),
 ('P82022', 'HALLIWELL SURGERY 1', 2.6902312553464682, 1124),
 ('P85013', 'THE ROYTON & CROMPTON FAMILY PRACTICE', 2.667409950287062, 2054),
 ('B81069',
  'PRACTICE 3  MEDICAL CENTRE  BRIDLINGTON',
  2.6526642039852844,
  1936),
 ('Y05493', 'LCWUCC - IUC NCL', 2.5927932420214392, 443),
 ('P84032', 'DR MOKASHI', 2.496887689055938, 1341),
 ('L81095', 'THE CREST FAMILY PRACTICE', 2.494358442548829, 1294),
 ('P85608', 'PERKINS PRACTICE', 2.479571342887134, 899),
 ('M91025', 'DARLASTON HEALTH CENTRE', 2.4456345065842657, 996),
 ('Y00469', "DR MA SIMS' PRACTICE", 2.437276610645611, 1857),
 ('P87652', '1/LOWER BROUGHTON MEDICAL PRACTICE', 2.435636753514273, 1044),
 ('G81013', 'CORNWALLIS PLAZA SURGERY', 2.424202462055629, 2326),
 ('Y02606', 'FAIRMORE MEDICAL PRACTICE', 2.3824085989710504, 1288),
 ('M82619', 'LAWLEY MEDICAL PRACTICE', 2.373577973078906, 1409),
 ('P83021', "PEEL GP'S", 2.353594338493154, 1557),
 ('P84051', 'EASTLANDS MEDICAL CENTRE', 2.325396683274206, 1369),
 ('N84010', 'MAGHULL HEALTH CENTRE (DR SAPRE)', 2.3194074094375097, 1322),
 ('Y00390', 'INTEGRATED CARE 24 LIMITED OOH', 2.3106497615538943, 511),
 ('Y02521', 'WILLOW BANK SURGERY', 2.295642132037915, 1934),
 ('Y03819', 'IC24 LTD (HWLH OOH)', 2.2949004338925127, 216),
 ('A81011', 'CHADWICK PRACTICE', 2.2917945205697303, 1568),
 ('M86639', 'C&WPT OOH SERVICE', 2.2708524012737876, 341),
 ('L81094', 'THE MERRYWOOD PRACTICE', 2.2705509556396586, 1234),
 ('Y03656', 'LEYLAND SURGERY', 2.251774286539937, 1213),
 ('P87008', 'WALKDEN MEDICAL PRACTICE', 2.2415736140706994, 1577),
 ('P83007', 'RADCLIFFE MEDICAL PRACTICE', 2.2396070334595315, 1553),
 ('P83005', 'RIBBLESDALE GP-DR SUBBIAH', 2.2097458912614827, 1100),
 ('P84637', 'THE MAZHARI & KHAN PRACTICE', 2.2006627122644895, 912),
 ('B81112', 'JAMES ALEXANDER FAMILY PRACTICE', 2.1967025909056024, 1634),
 ('Y01838', 'B&H INTERMEDIATE CARE SERVICE', 2.1862131918267544, 456),
 ('M91022', 'HARDEN SURGERY', 2.155495816284959, 1228),
 ('G82044', 'THE GATEWAY MEDICAL PRACTICE', 2.154423496545371, 1349),
 ('P85026', 'QUAYSIDE MEDICAL PRACTICE', 2.1535448371359025, 1422),
 ('Y00599', 'HASTINGS AND ROTHER OOH', 2.076490970994684, 291),
 ('L81013', 'FISHPONDS FAMILY PRACTICE', 2.0743592136603786, 1632),
 ('A89019', 'DRS CLOAK  CHOI AND MILLIGAN', 2.0511156727220916, 1661),
 ('M91612', "ST MARY'S SURGERY", 2.041026500575296, 981),
 ('P81079', 'THE THORNTON PRACTICE', 1.9970130183083867, 1970),
 ('Y04588', 'IC24 LTD (EAST SURREY OOH)', 1.9530599800408153, 194),
 ('P84043', 'CORNISHWAY GROUP PRACTICE', 1.9529030654485127, 1506),
 ('P92621', 'PREMIER HEALTH TEAM', 1.9342677920567377, 876),
 ('A89022', 'CONCORD MEDICAL PRACTICE', 1.9339605744520654, 1386),
 ('A81058', 'COULBY MEDICAL PRACTICE', 1.9268085445885355, 1585),
 ('C84064', 'PARKSIDE MEDICAL CENTRE', 1.9235518278308144, 1314),
 ('A81064', 'THE DISCOVERY PRACTICE', 1.9047661015943373, 1268),
 ('B81026', 'ANCORA MEDICAL PRACTICE', 1.8854159223309173, 2347),
 ('P81140', 'DARWEN HEALTHLINK', 1.8822754121466374, 2019),
 ('P85601', 'JALAL PRACTICE', 1.8661104279692895, 885),
 ('B83042', 'ROOLEY LANE MED. CENTRE', 1.8635817801511316, 1522),
 ('N82669', 'GREAT HOMER STREET MEDICAL CENTRE', 1.813002119840964, 1062),
 ('Y02344', 'NORTHPOINT', 1.8024326949572382, 1137),
 ('P81092', 'THE CRESCENT SURGERY', 1.7989165864147443, 1734),
 ('N81096', 'BROOKVALE PRACTICE', 1.7979440966591638, 1484),
 ('Y00675', 'LEIGH NHS WIC', 1.7760099128664424, 162),
 ('B87006', 'DR SP SINGH AND PARTNERS', 1.772041643578181, 1840),
 ('B82092', 'BELGRAVE SURGERY', 1.7643723369327995, 1291),
 ('P85006', 'THE PARKS MEDICAL PRACTICE', 1.7589687048174796, 1466),
 ('F81106', 'THE ROSS PRACTICE', 1.7231557395207378, 1648),
 ('D81024', 'THOMAS WALKER', 1.69692378556541, 1377),
 ('A81033', 'OAKFIELD MEDICAL PRACTICE', 1.6948316951338191, 1055),
 ('P81684', "DR DP CHARLES' PRACTICE", 1.691315520903282, 1353),
 ('N81121', 'NORTHGATE VILLAGE SURGERY', 1.6861842319656928, 1304),
 ('P81099', 'DR THM MACKENZIE & PARTNERS', 1.682911604319903, 1782)]

In [103]:
#anomalies = [("NATIONAL ENHANCED SERVICE", 11.6958178629, 7)] * 100

In [164]:
grader.score.dw__script_anomalies(anomalies)

==================
Your score: 1.000
==================

#### For finding hospitals that prescribe unnecessary opioid drugs on large amounts each time(eg:everymonth dataset) we can create a method  called find_anomalies that takes 3 dataframes (scripts,practices,chem) as arguments and return the dataframe containing the details of the top 100 hospitals promoting drug abuse.

In [105]:
#def find_anomalies(scripts, practices,chem):
#    opioids = ['morphine', 'oxycodone', 'methadone', 'fentanyl', 'pethidine', 'buprenorphine', 'propoxyphene', 'codeine']
#    opioid_codes = chem[chem['NAME'].str.contains('|'.join(opioids), case=False)]['CHEM SUB'].unique()
#    ............

## Question 5: script_growth

Another way to identify anomalies is by comparing current data to historical data. In the case of identifying sites of drug abuse, we might compare a practice's current rate of opioid prescription to their rate 5 or 10 years ago. Unless the nature of the practice has changed, the profile of drugs they prescribe should be relatively stable. We might also want to identify trends through time for business reasons, identifying drugs that are gaining market share. That's what we'll do in this question.

We'll load in beneficiary data from 6 months earlier, June 2016, and calculate the growth rate in prescription rate from June 2016 to January 2017 for each `bnf_name`. The growth is defined as

$$
\text{growth rate} = \frac{x_1 - x_0}{x_0},
$$
where $x_1$ is the current value and $x_0$ is the previous value.


We'll return the 50 items with largest growth and the 50 items with the largest shrinkage (i.e. negative growth rate) as a list of tuples sorted by growth rate in descending order in the format `(script_name, growth_rate, raw_2016_count)`. You'll notice that many of the 50 fastest growing items have low counts of prescriptions in 2016. Filter out any items that were prescribed less than 50 times.

In [106]:
scripts16 = pd.read_csv('dw-data/201606scripts_sample.csv.gz')

In [107]:
scripts16.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity
0,N85638,0301011R0,Salamol_Inha 100mcg (200 D) CFF (Teva),2,2.92,2.73,2
1,N85638,0301011R0,Easyhaler_Salbutamol Sulf 200mcg (200D),1,6.63,6.15,1
2,N85638,0301020I0,Ipratrop Brom_Inh Soln 500mcg/2ml Ud,1,1.77,1.75,12
3,N85638,0301020I0,Ipratrop Brom_Inh Soln 250mcg/1ml Ud,1,4.47,4.15,20
4,N85638,0302000C0,Clenil Modulite_Inha 50mcg (200D),1,3.70,3.44,1

In [108]:
bnf_totals_2016 =  scripts16['bnf_name'].value_counts()

In [109]:
bnf_totals_2016
#Xo

GlucoRX FinePoint Needles Pen Inj Screw     1532
3m Health Care_Cavilon Durable Barrier C     825
Fluclox Sod_Cap 500mg                        796
Amoxicillin_Cap 500mg                        790
Prednisolone_Tab 5mg                         786
                                            ...
Azapress_Tab 50mg                              1
Jade_Adult Male Urin + Pressure Ring Dia       1
DBT_Dry Aid D/S Hydrocolloid Sheath Line       1
Lid-Care_Eyelid Wipe                           1
Sucralfate_Enem 2g In 50ml                     1
Name: bnf_name, Length: 13540, dtype: int64

In [110]:
bnf_totals_2017 = scripts['bnf_name'].value_counts()

In [111]:
bnf_totals_2017
#X1

GlucoRX FinePoint Needles Pen Inj Screw     1718
3m Health Care_Cavilon Durable Barrier C     816
Prednisolone_Tab 5mg                         785
Fluclox Sod_Cap 500mg                        783
Amoxicillin_Cap 500mg                        777
                                            ...
Skinnies Silk Shorts Adult Med Silk Garm       1
Jobst Elvarex For L/Extrem Class 3 Foot        1
Altipress Short Exlge Compress Liner Pac       1
Promethazine HCl_Inj 25mg/ml 1ml Amp           1
Zorac_Aq Gel 0.05%                             1
Name: bnf_name, Length: 13471, dtype: int64

In [112]:
growth_rate = (bnf_totals_2017-bnf_totals_2016)/bnf_totals_2016

In [113]:
growth_rate

365 Film 10cm x 12cm VP Adh Film Dress           NaN
365 Film 15cm x 20cm VP Adh Film Dress           NaN
365 Film 4cm x 5cm VP Adh Film Dress             NaN
365 Non Adherent 10cm x 10cm Pfa Plas Fa    0.000000
365 Non Adherent 10cm x 20cm Pfa Plas Fa         NaN
                                              ...
nSpire PiKo-1 Stnd Range Peak Flow Meter   -0.500000
nSpire Pocket Peak Low Range Peak Flow M    1.000000
nSpire Pocket Peak Stnd Range Peak Flow     1.500000
oraNurse_Toothpaste Orig (1450ppm)          1.000000
palmdoc (Reagent)_Strips                    0.666667
Name: bnf_name, Length: 15424, dtype: float64

In [114]:
growth_rate.rename('growth_rate')

365 Film 10cm x 12cm VP Adh Film Dress           NaN
365 Film 15cm x 20cm VP Adh Film Dress           NaN
365 Film 4cm x 5cm VP Adh Film Dress             NaN
365 Non Adherent 10cm x 10cm Pfa Plas Fa    0.000000
365 Non Adherent 10cm x 20cm Pfa Plas Fa         NaN
                                              ...
nSpire PiKo-1 Stnd Range Peak Flow Meter   -0.500000
nSpire Pocket Peak Low Range Peak Flow M    1.000000
nSpire Pocket Peak Stnd Range Peak Flow     1.500000
oraNurse_Toothpaste Orig (1450ppm)          1.000000
palmdoc (Reagent)_Strips                    0.666667
Name: growth_rate, Length: 15424, dtype: float64

In [115]:
pd.concat([growth_rate.rename('growth_rate'),bnf_totals_2016.rename('count')],axis=1)

                                          growth_rate  count
365 Film 10cm x 12cm VP Adh Film Dress            NaN    NaN
365 Film 15cm x 20cm VP Adh Film Dress            NaN    1.0
365 Film 4cm x 5cm VP Adh Film Dress              NaN    1.0
365 Non Adherent 10cm x 10cm Pfa Plas Fa     0.000000    3.0
365 Non Adherent 10cm x 20cm Pfa Plas Fa          NaN    NaN
...                                               ...    ...
nSpire PiKo-1 Stnd Range Peak Flow Meter    -0.500000    2.0
nSpire Pocket Peak Low Range Peak Flow M     1.000000    2.0
nSpire Pocket Peak Stnd Range Peak Flow      1.500000    2.0
oraNurse_Toothpaste Orig (1450ppm)           1.000000    2.0
palmdoc (Reagent)_Strips                     0.666667    3.0

[15424 rows x 2 columns]

In [116]:
df = pd.concat([growth_rate.rename('growth_rate'),
           bnf_totals_2016.rename('count')],axis=1).reset_index()\
           .rename(columns={'index':'bnf_name'})

In [117]:
df

                                       bnf_name  growth_rate  count
0        365 Film 10cm x 12cm VP Adh Film Dress          NaN    NaN
1        365 Film 15cm x 20cm VP Adh Film Dress          NaN    1.0
2          365 Film 4cm x 5cm VP Adh Film Dress          NaN    1.0
3      365 Non Adherent 10cm x 10cm Pfa Plas Fa     0.000000    3.0
4      365 Non Adherent 10cm x 20cm Pfa Plas Fa          NaN    NaN
...                                         ...          ...    ...
15419  nSpire PiKo-1 Stnd Range Peak Flow Meter    -0.500000    2.0
15420  nSpire Pocket Peak Low Range Peak Flow M     1.000000    2.0
15421   nSpire Pocket Peak Stnd Range Peak Flow     1.500000    2.0
15422        oraNurse_Toothpaste Orig (1450ppm)     1.000000    2.0
15423                  palmdoc (Reagent)_Strips     0.666667    3.0

[15424 rows x 3 columns]

In [118]:
df[df['count']>=50] 
#filtering out rows having count<50(given in Q)

                                       bnf_name  growth_rate  count
16     3m Health Care_Cavilon Durable Barrier C    -0.010909  825.0
17     3m Health Care_Cavilon No Sting 1ml Barr    -0.034632  231.0
18     3m Health Care_Cavilon No Sting 3ml Barr    -0.104762  105.0
19      3m Health Care_Cavilon No Sting Barrier    -0.092511  454.0
22            A.S Saliva Orthana Spy 50ml (App)     0.440476   84.0
...                                         ...          ...    ...
15326     Zuclopenth Decan_Inj 200mg/ml 1ml Amp    -0.383562   73.0
15327     Zuclopenth Decan_Inj 500mg/ml 1ml Amp    -0.259259   54.0
15328                   Zuclopenth HCl_Tab 10mg     0.051724  116.0
15330                    Zuclopenth HCl_Tab 2mg     0.014085   71.0
15331                           Zumenon_Tab 1mg    -0.215686   51.0

[3519 rows x 3 columns]

In [119]:
df[df['count']>=50].sort_values('growth_rate',ascending=False)

                                       bnf_name  growth_rate  count
1985            Butec_Transdermal Patch 5mcg/hr     3.467742   62.0
1983           Butec_Transdermal Patch 10mcg/hr     3.000000   69.0
5742   Fostair NEXThaler_Inh 200mcg/6mcg (120D)     1.430233   86.0
11270     Pneumococcal_Vac 0.5ml Vl (23 Valent)     1.269430  193.0
13357  Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev     1.269231   52.0
...                                         ...          ...    ...
13351               Spatone Iron-Plus_Sach 20ml          NaN   98.0
13659                  TRUEone (Reagent)_Strips          NaN   70.0
13675                     Tabphyn_MR Cap 400mcg          NaN   87.0
13910                       Testosterone_Gel 2%          NaN  190.0
13999                  Timolol_Eye Dps 0.25% Ud          NaN   51.0

[3519 rows x 3 columns]

In [120]:
df[(df['count']>=50) & (~df['growth_rate'].isna())]

                                       bnf_name  growth_rate  count
16     3m Health Care_Cavilon Durable Barrier C    -0.010909  825.0
17     3m Health Care_Cavilon No Sting 1ml Barr    -0.034632  231.0
18     3m Health Care_Cavilon No Sting 3ml Barr    -0.104762  105.0
19      3m Health Care_Cavilon No Sting Barrier    -0.092511  454.0
22            A.S Saliva Orthana Spy 50ml (App)     0.440476   84.0
...                                         ...          ...    ...
15326     Zuclopenth Decan_Inj 200mg/ml 1ml Amp    -0.383562   73.0
15327     Zuclopenth Decan_Inj 500mg/ml 1ml Amp    -0.259259   54.0
15328                   Zuclopenth HCl_Tab 10mg     0.051724  116.0
15330                    Zuclopenth HCl_Tab 2mg     0.014085   71.0
15331                           Zumenon_Tab 1mg    -0.215686   51.0

[3485 rows x 3 columns]

In [121]:
df = df[(df['count']>=50) & (~df['growth_rate'].isna())].sort_values('growth_rate',ascending=False)

In [122]:
df

                                       bnf_name  growth_rate  count
1985            Butec_Transdermal Patch 5mcg/hr     3.467742   62.0
1983           Butec_Transdermal Patch 10mcg/hr     3.000000   69.0
5742   Fostair NEXThaler_Inh 200mcg/6mcg (120D)     1.430233   86.0
11270     Pneumococcal_Vac 0.5ml Vl (23 Valent)     1.269430  193.0
13357  Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev     1.269231   52.0
...                                         ...          ...    ...
6885         Hydroxyzine HCl_Oral Soln 10mg/5ml    -0.914894   94.0
10590                               Ovysmen_Tab    -0.925373   67.0
2646                           Climaval_Tab 1mg    -0.926471  136.0
2648                               Climesse_Tab    -0.942029   69.0
11297                      Polyalc_Eye Dps 1.4%    -0.996324  272.0

[3485 rows x 3 columns]

In [123]:
script_growth = pd.concat([df.head(50),df.tail(50)])

In [124]:
len(script_growth)

100

In [125]:
script_growth

                                       bnf_name  growth_rate  count
1985            Butec_Transdermal Patch 5mcg/hr     3.467742   62.0
1983           Butec_Transdermal Patch 10mcg/hr     3.000000   69.0
5742   Fostair NEXThaler_Inh 200mcg/6mcg (120D)     1.430233   86.0
11270     Pneumococcal_Vac 0.5ml Vl (23 Valent)     1.269430  193.0
13357  Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev     1.269231   52.0
...                                         ...          ...    ...
6885         Hydroxyzine HCl_Oral Soln 10mg/5ml    -0.914894   94.0
10590                               Ovysmen_Tab    -0.925373   67.0
2646                           Climaval_Tab 1mg    -0.926471  136.0
2648                               Climesse_Tab    -0.942029   69.0
11297                      Polyalc_Eye Dps 1.4%    -0.996324  272.0

[100 rows x 3 columns]

In [126]:
script_growth = [item[1:] for item in script_growth.itertuples()]

In [127]:
script_growth

[('Butec_Transdermal Patch 5mcg/hr', 3.467741935483871, 62.0),
 ('Butec_Transdermal Patch 10mcg/hr', 3.0, 69.0),
 ('Fostair NEXThaler_Inh 200mcg/6mcg (120D)', 1.430232558139535, 86.0),
 ('Pneumococcal_Vac 0.5ml Vl (23 Valent)', 1.2694300518134716, 193.0),
 ('Spiolto Respimat_Inha2.5/2.5mcg(60D)+Dev', 1.2692307692307692, 52.0),
 ('Trulicity_Inj 1.5mg/0.5ml Pf Pen', 1.1851851851851851, 54.0),
 ('CosmoCol_Paed Oral Pdr Sach 6.9g', 1.1774193548387097, 62.0),
 ('Dulaglutide_Inj 1.5mg/0.5ml Pf Dev', 0.9634146341463414, 82.0),
 ('ViATIM_Vac D/Chamber 160u/25mcg 1ml Pfs', 0.912, 125.0),
 ('Empagliflozin_Tab 25mg', 0.896, 125.0),
 ('CareSens Lancets 0.31mm/30 Gauge', 0.8955223880597015, 67.0),
 ('Fostair_Inh 200mcg/6mcg (120D) CFF', 0.8616600790513834, 253.0),
 ('Orbis Nor Saline Sod Chlor 0.9% Nsl Dps', 0.8588235294117647, 85.0),
 ('Umeclidinium Brom_Inh 65mcg (30D)', 0.8275862068965517, 87.0),
 ('Ultibro Breezhaler_Pdr Inh Cap + Dev', 0.8016528925619835, 121.0),
 ('Medihoney_Barrier Crm', 0.7840909090909091, 88.0),
 ('Fluoxetine HCl_Oral Soln 20mg/5ml S/F', 0.7808219178082192, 73.0),
 ('TEE2 (Reagent)_Strips', 0.7777777777777778, 81.0),
 ('Zaluron XL_Tab 400mg', 0.7586206896551724, 58.0),
 ('Laxido_Paed Plain Oral Pdr Sach 6.9g', 0.7586206896551724, 174.0),
 ('Prednisolone_Oral Soln 5mg/5ml Ud', 0.726027397260274, 73.0),
 ('Buprenorphine_Patch 15mcg/hr (7day)', 0.7155963302752294, 109.0),
 ('Coloplast_SenSura Mio Maxi Drnbl Bag S/C', 0.7037037037037037, 81.0),
 ('Octenisan_Antimicrobial Wsh Lot', 0.7027027027027027, 74.0),
 ('Duaklir Genuair_340mcg/12mcg (60D)', 0.6710526315789473, 152.0),
 ('Sod Chlor_Inh Soln 0.9% 2.5ml Ud Amp', 0.6419753086419753, 162.0),
 ('Coloplast_SenSura Mio Maxi Drnbl Bag L/C', 0.6274509803921569, 51.0),
 ('Flutiform_Inha 50/5mcg (120 D)', 0.625, 88.0),
 ('Ins Degludec_100u/ml 3ml Pf Pen', 0.6166666666666667, 60.0),
 ('CareSens Lancets 0.36mm/28 Gauge', 0.6111111111111112, 90.0),
 ('Epimax Crm 500g', 0.61, 100.0),
 ('Evacal D3_Tab Chble 400u/1.5g', 0.6046511627906976, 86.0),
 ('Shortec_Cap 20mg', 0.6029411764705882, 68.0),
 ('Co-Trimoxazole_Oral Susp 40/200mg/5mlS/F', 0.6, 50.0),
 ('Ciprofloxacin_Gran For Susp 250mg/5ml', 0.5921052631578947, 76.0),
 ('AgaMatrix Ultra-Thin Lancets 0.35mm/28 G', 0.5660377358490566, 53.0),
 ('Zemtard 120 XL_Cap 120mg', 0.5636363636363636, 55.0),
 ('Nutramigen 2 + LGG_Pdr', 0.5604395604395604, 91.0),
 ('Toujeo_300u/ml 1.5ml Pf SoloStar Pen', 0.5408805031446541, 159.0),
 ('Ins Tresiba_FlexTouch 100u/ml 3ml Pf Pen', 0.5405405405405406, 148.0),
 ('Longtec_Tab 30mg M/R', 0.5370370370370371, 108.0),
 ('Adalat_Cap 5mg', 0.5365853658536586, 82.0),
 ('Dexameth_Oral Soln 2mg/5ml S/F', 0.5294117647058824, 68.0),
 ('Haloperidol_Inj 5mg/ml 1ml Amp', 0.5288461538461539, 104.0),
 ('Lyclear_Dermal Crm 5%', 0.5211267605633803, 71.0),
 ('Valupak_Multivit & Mineral Tab OAD', 0.5098039215686274, 51.0),
 ('Coloplast_Sensura Mio Maxi Clsd Bag + Fl', 0.5056179775280899, 89.0),
 ('Medikinet XL_Cap 10mg', 0.48484848484848486, 99.0),
 ('Dovobet_Gel Applic', 0.48148148148148145, 54.0),
 ('Incruse Ellipta_Inh 55mcg (30D)', 0.4807692307692308, 208.0),
 ('Oxycodone HCl_Tab 20mg M/R', -0.4318181818181818, 264.0),
 ('Cardura XL_Tab 4mg', -0.43478260869565216, 69.0),
 ('Oxycodone HCl_Tab 80mg M/R', -0.4358974358974359, 78.0),
 ('Verapamil HCl_Cap 120mg M/R', -0.43790849673202614, 153.0),
 ('Topamax_Tab 100mg', -0.45161290322580644, 62.0),
 ('Opticrom_Allergy Eye Dps 2%', -0.4523809523809524, 126.0),
 ('Optilast_Eye Dps 0.05%', -0.45454545454545453, 55.0),
 ('Actonel_Once a Week Tab 35mg', -0.4576271186440678, 59.0),
 ('Premique_Tab 0.625mg/5mg', -0.47039473684210525, 304.0),
 ('Sunsense_Daily Face Crm Spf 50+', -0.48344370860927155, 151.0),
 ('Hydrocort/Crotamiton_Crm 0.25%/10%', -0.48936170212765956, 141.0),
 ('Azelastine HCl_Aq Eye Dps 0.05%', -0.5036231884057971, 276.0),
 ('Opticrom_Eye Dps 2% (Aq)', -0.5073891625615764, 203.0),
 ('Metoprolol Tart_Tab 200mg M/R', -0.509090909090909, 55.0),
 ('Rapitil_Eye Dps 2%', -0.5096774193548387, 155.0),
 ('Desloratadine_Oral Soln 2.5mg/5ml S/F', -0.5147058823529411, 136.0),
 ('Erythromycin_Ethylsuc Tab 500mg', -0.5154639175257731, 97.0),
 ('Aquacel Foam Adhesive 8cm x 8cm Wound Dr', -0.5294117647058824, 68.0),
 ('Zirtek_Allergy Tab 10mg', -0.5303030303030303, 66.0),
 ('Antaz Sulf/Xylomet_Eye Dps 0.5%/0.05%', -0.5454545454545454, 66.0),
 ('Vital 1.5kcal_Liq (Vanilla)', -0.5466666666666666, 75.0),
 ('Oxybutynin HCl_Oral Soln 2.5mg/5ml S/F', -0.5573770491803278, 61.0),
 ('Prazosin HCl_Tab 500mcg', -0.5581395348837209, 86.0),
 ('Artificial Saliva_Spy 50ml', -0.5586854460093896, 213.0),
 ('Sunsense_Ultra Lot Spf 50+', -0.5652173913043478, 368.0),
 ('Telfast 120_Tab 120mg', -0.5698924731182796, 93.0),
 ('Otrivine-Antistin_Eye Dps', -0.572463768115942, 138.0),
 ('Fexofenadine HCl_Tab 30mg', -0.5959595959595959, 297.0),
 ('Mag Trisil_Mix', -0.6119402985074627, 67.0),
 ('Glibenclamide_Tab 5mg', -0.6164383561643836, 146.0),
 ('Co-Danthrusate_Cap 50mg/60mg', -0.6296296296296297, 81.0),
 ('Ketotifen Fumar_Eye Dps 250mcg/ml', -0.6842105263157895, 57.0),
 ('Uvistat_Sun Crm Spf 50', -0.6917293233082706, 133.0),
 ('Haelan_Tape 7.5cm x 50cm', -0.7130434782608696, 115.0),
 ('Haelan_Tape 7.5cm x 20cm', -0.72, 100.0),
 ('Beconase_Hayfever Nsl Spy 50mcg (180 D)', -0.7384615384615385, 65.0),
 ('Uvistat_Sun Crm Spf 30', -0.7647058823529411, 68.0),
 ('Deep Freeze_Cold Gel 2%', -0.7758620689655172, 58.0),
 ('Adizem-SR_Tab 120mg', -0.8269230769230769, 52.0),
 ('Anugesic HC_Crm', -0.8541666666666666, 96.0),
 ('Sunsense_Sunsensitive Crm SPF 50+', -0.8562091503267973, 153.0),
 ('Hepatyrix_Vac 1440u/25mcg/ml 1ml Pfs', -0.875, 216.0),
 ('Climagest_Tab 2mg', -0.8939393939393939, 66.0),
 ('Climaval_Tab 2mg', -0.9015151515151515, 132.0),
 ('Orphenadrine HCl_Tab 50mg', -0.9117647058823529, 102.0),
 ('Hydroxyzine HCl_Oral Soln 10mg/5ml', -0.9148936170212766, 94.0),
 ('Ovysmen_Tab', -0.9253731343283582, 67.0),
 ('Climaval_Tab 1mg', -0.9264705882352942, 136.0),
 ('Climesse_Tab', -0.9420289855072463, 69.0),
 ('Polyalc_Eye Dps 1.4%', -0.9963235294117647, 272.0)]

In [128]:
#script_growth = [("Butec_Transdermal Patch 5mcg\/hr", 3.4677419355, 62.0)] * 100

In [165]:
grader.score.dw__script_growth(script_growth)

==================
Your score: 1.000
==================

## Question 6: rare_scripts

Does a practice's prescription costs originate from routine care or from reliance on rarely prescribed treatments? Commonplace treatments can carry lower costs than rare treatments because of efficiencies in large-scale production. While some specialist practices can't help but avoid prescribing rare medicines because there are no alternatives, some practices may be prescribing a unnecessary amount of brand-name products when generics are available. Let's identify practices whose costs disproportionately originate from rarely prescribed items.

First we have to identify which `'bnf_code'` are rare. To do this, find the probability $p$ of a prescription having a particular `'bnf_code'` if the `'bnf_code'` was randomly chosen from the unique options in the beneficiary data. We will call a `'bnf_code'` rare if it is prescribed at a rate less than $0.1p$.

In [130]:
len(set(scripts['bnf_code']))

1975

In [131]:
scripts['bnf_code'].unique() # numpy array

array(['0106020C0', '0106040M0', '0301011R0', ..., '0606010T0',
       '237541075', '236041060'], dtype=object)

In [132]:
len(scripts['bnf_code'].unique())

1975

In [133]:
scripts['bnf_code'].nunique()

1975

In [134]:
p = 1/scripts['bnf_code'].nunique() 
# probability of getting a bnf_code  from thr unique set of bnf_codes

In [135]:
p

0.0005063291139240507

In [136]:
scripts['bnf_code'].value_counts()

0906040G0    14442
090402000    10721
0302000N0     9940
130201000     8602
0601060D0     8563
             ...
210300004        1
228062080        1
0908010AL        1
0503010G0        1
030902040        1
Name: bnf_code, Length: 1975, dtype: int64

In [137]:
scripts['bnf_code'].count()

973193

In [138]:
rates = scripts['bnf_code'].value_counts() / scripts['bnf_code'].count()
                                         #OR
# rates = scripts['bnf_code'].value_counts(normalize=True)
# probability from actual data set.

In [139]:
rates

0906040G0    0.014840
090402000    0.011016
0302000N0    0.010214
130201000    0.008839
0601060D0    0.008799
               ...
210300004    0.000001
228062080    0.000001
0908010AL    0.000001
0503010G0    0.000001
030902040    0.000001
Name: bnf_code, Length: 1975, dtype: float64

In [140]:
rates < 0.1*p

0906040G0    False
090402000    False
0302000N0    False
130201000    False
0601060D0    False
             ...
210300004     True
228062080     True
0908010AL     True
0503010G0     True
030902040     True
Name: bnf_code, Length: 1975, dtype: bool

In [141]:
rates[rates < 0.1*p]

239448100    0.000050
1001030F0    0.000050
236001063    0.000050
0503021E0    0.000050
0402010P0    0.000050
               ...
210300004    0.000001
228062080    0.000001
0908010AL    0.000001
0503010G0    0.000001
030902040    0.000001
Name: bnf_code, Length: 844, dtype: float64

In [142]:
set(rates[rates < 0.1*p].index)

{'0101010C0',
 '0101010F0',
 '0101010I0',
 '0101010J0',
 '0101010N0',
 '0101010P0',
 '0101010Q0',
 '0101012B0',
 '010102100',
 '0101021C0',
 '0102000AC',
 '0102000D0',
 '010300000',
 '0103020P0',
 '0103030W0',
 '0103040M0',
 '0104020H0',
 '0104020N0',
 '0104020P0',
 '0104030A0',
 '0105020C0',
 '0105020G0',
 '010602000',
 '0106020B0',
 '0106020J0',
 '0106030A0',
 '0106030P0',
 '0106040J0',
 '0106040L0',
 '0106040X0',
 '0106050B0',
 '0106050M0',
 '0106060B0',
 '0106070C0',
 '010701000',
 '0108010S0',
 '0109010R0',
 '0202010D0',
 '0202010J0',
 '0202010L0',
 '0202010Y0',
 '0202040G0',
 '0202040H0',
 '0202040T0',
 '0202040U0',
 '0202040V0',
 '0203020G0',
 '0203020P0',
 '0203020U0',
 '020400030',
 '0204000N0',
 '0204000P0',
 '0205010AB',
 '0205010Y0',
 '0205040I0',
 '0205040M0',
 '0205051AA',
 '0205051AB',
 '0205051AC',
 '0205051E0',
 '0205051G0',
 '0205051P0',
 '0205051S0',
 '0205052AC',
 '0205052AD',
 '0206020B0',
 '0206020I0',
 '0206020M0',
 '0206040AF',
 '0206040AI',
 '0207030A0',
 '0208010AB',
 '0208010K0',
 '0208010N0',
 '0208020I0',
 '0208020N0',
 '0212000A0',
 '0212000AJ',
 '0212000K0',
 '0301011B0',
 '0301011Z0',
 '0301012F0',
 '0302000R0',
 '0303010J0',
 '0303010Q0',
 '0303030B0',
 '0304010AG',
 '0304010H0',
 '0304010K0',
 '0304020P0',
 '030800000',
 '0308000B0',
 '0308000M0',
 '0309010L0',
 '030902040',
 '0309020B0',
 '0309020G0',
 '0309020H0',
 '0309020I0',
 '0309020R0',
 '0310000E0',
 '0310000Q0',
 '040101000',
 '0401010AC',
 '0401010C0',
 '0401010D0',
 '0401020R0',
 '0401030E0',
 '0401030H0',
 '0401030T0',
 '0402010AE',
 '0402010AI',
 '0402010B0',
 '0402010C0',
 '0402010I0',
 '0402010P0',
 '0402010Q0',
 '0402010R0',
 '0402020AD',
 '0402020V0',
 '0402030P0',
 '0402030R0',
 '0403010T0',
 '0403020H0',
 '0403020Q0',
 '0403040S0',
 '0404000V0',
 '0406000AC',
 '0406000AD',
 '0406000AF',
 '0406000E0',
 '0406000M0',
 '0406000R0',
 '0406000W0',
 '040701000',
 '0407010AC',
 '0407010M0',
 '0407010W0',
 '0407010X0',
 '0407020H0',
 '0407020T0',
 '0407041F0',
 '0407041U0',
 '0408010AA',
 '0408010AB',
 '0408010AG',
 '0408010AJ',
 '0408010AL',
 '0408010Y0',
 '0408020Q0',
 '0409010AA',
 '0409010AB',
 '0409010P0',
 '0409010S0',
 '0409010U0',
 '0409020E0',
 '0409030B0',
 '0409030P0',
 '0410010D0',
 '0410020D0',
 '0410030B0',
 '0410030D0',
 '0501011J0',
 '0501013C0',
 '0501013E0',
 '0501021B0',
 '0501021C0',
 '0501021G0',
 '0501021H0',
 '0501021K0',
 '0501022A0',
 '0501022B0',
 '0501023A0',
 '0501030F0',
 '0501040H0',
 '0501040N0',
 '0501040U0',
 '0501070AB',
 '0501070F0',
 '0501070M0',
 '0501070N0',
 '0501070T0',
 '0501070U0',
 '0501070W0',
 '0501080J0',
 '0501080V0',
 '0501090H0',
 '0501090N0',
 '0501090Q0',
 '0501090S0',
 '0501110G0',
 '0501120Q0',
 '0501120Y0',
 '0502010D0',
 '0502020A0',
 '0502030A0',
 '0502050B0',
 '0503010AA',
 '0503010G0',
 '0503010H0',
 '0503010Q0',
 '0503021D0',
 '0503021E0',
 '0503022B0',
 '0503031B0',
 '0504010F0',
 '0504010L0',
 '0504010N0',
 '0504010U0',
 '0504040M0',
 '0505020L0',
 '0505030A0',
 '0505050P0',
 '0505060I0',
 '0601012G0',
 '0601012U0',
 '0601023AH',
 '0601023AL',
 '0601023AP',
 '0601023AR',
 '0601040E0',
 '0602010Z0',
 '0602020G0',
 '0603020AA',
 '0603020F0',
 '0603020H0',
 '0603020I0',
 '0603020L0',
 '0603020M0',
 '0603020S0',
 '0603020X0',
 '0604011AD',
 '0604011D0',
 '0604011H0',
 '0604011J0',
 '0604020D0',
 '0604020F0',
 '0604020M0',
 '0604030Q0',
 '0605010D0',
 '0605010G0',
 '0605010N0',
 '0605010T0',
 '0605020Y0',
 '0606010T0',
 '0606010U0',
 '060602000',
 '0606020Y0',
 '0607010T0',
 '0607020C0',
 '0607020P0',
 '0607020Y0',
 '0607030M0',
 '0702020H0',
 '0702020T0',
 '0703010M0',
 '0703010R0',
 '0703010S0',
 '0703022N0',
 '0703030G0',
 '0704010C0',
 '0704010I0',
 '070403000',
 '0704030J0',
 '0704040D0',
 '0704050AD',
 '0704050J0',
 '0704050Y0',
 '0704060A0',
 '0801000I0',
 '0801000T0',
 '0801010H0',
 '0801030P0',
 '0801030T0',
 '0802040AA',
 '0802040J0',
 '0803010K0',
 '0803041AA',
 '0803042H0',
 '0803042S0',
 '0803043P0',
 '0901012I0',
 '0901012K0',
 '0901030D0',
 '0901030E0',
 '0901030K0',
 '0901030N0',
 '0901030R0',
 '0901040A0',
 '0901060I0',
 '0902011L0',
 '0902011P0',
 '0902013P0',
 '0902021N0',
 '0902021Q0',
 '090401020',
 '090401050',
 '090401060',
 '0904010AE',
 '0904010AH',
 '0904010AI',
 '0904010AK',
 '0904010AL',
 '0904010AM',
 '0904010AN',
 '0904010AP',
 '0904010AR',
 '0904010AS',
 '0904010AT',
 '0904010E0',
 '0904010T0',
 '0904010V0',
 '0904010Z0',
 '0905011K0',
 '0905011R0',
 '090501300',
 '0905013F0',
 '0905013N0',
 '0905013P0',
 '0905022U0',
 '0905022W0',
 '090504100',
 '090504700',
 '090504800',
 '0905050A0',
 '090601100',
 '0906012B0',
 '090602200',
 '0906022K0',
 '090602400',
 '090602500',
 '0906025P0',
 '090602700',
 '090602800',
 '090603100',
 '090603200',
 '0906040K0',
 '0906040P0',
 '090605000',
 '0906050U0',
 '0908010AJ',
 '0908010AL',
 '0908010C0',
 '0908010E0',
 '0908010N0',
 '0908010P0',
 '0908010T0',
 '0908010Z0',
 '0911010T0',
 '100101040',
 '100101050',
 '100101080',
 '1001010AD',
 '1001010AE',
 '1001010AM',
 '1001010AP',
 '1001010I0',
 '1001010S0',
 '1001010T0',
 '1001022G0',
 '1001022Y0',
 '1001030AA',
 '1001030F0',
 '1001030J0',
 '1001030Q0',
 '1001040A0',
 '1001040K0',
 '1001040P0',
 '1001050A0',
 '1001050B0',
 '1002010M0',
 '1002020Y0',
 '1003020M0',
 '1003020Y0',
 '1103010AG',
 '1103010AI',
 '1103010E0',
 '1103010S0',
 '1103010X0',
 '1103030W0',
 '1104010V0',
 '110402000',
 '1104020AB',
 '1104020AC',
 '1104020R0',
 '1104020X0',
 '1104020Y0',
 '1105000P0',
 '1105000S0',
 '1106000AM',
 '1106000Y0',
 '1107000M0',
 '1107000N0',
 '1107000Q0',
 '1108010A0',
 '1108010AA',
 '1108010Q0',
 '1108020A0',
 '1108020AH',
 '1108020K0',
 '1108020U0',
 '1108030AA',
 '1201010AC',
 '1201010H0',
 '1202010P0',
 '120202000',
 '1203010C0',
 '1203010F0',
 '1203010S0',
 '1203010U0',
 '1203030A0',
 '1203030F0',
 '1203030J0',
 '1203030M0',
 '1203030N0',
 '120304000',
 '1203040C0',
 '1203040G0',
 '1203040I0',
 '1203040N0',
 '1301010I0',
 '1301010P0',
 '1302010M0',
 '1302010Z0',
 '1302020F0',
 '1302020G0',
 '130203000',
 '1303000B0',
 '1303000E0',
 '1303000F0',
 '1303000M0',
 '1303000Q0',
 '130400000',
 '1304000B0',
 '1304000C0',
 '130501000',
 '1305010AF',
 '130502000',
 '1305020R0',
 '1305020S0',
 '1305020T0',
 '1306010A0',
 '1306010N0',
 '1306010T0',
 '1306020J0',
 '1307000C0',
 '1307000F0',
 '1308010U0',
 '130900000',
 '1309000F0',
 '1309000G0',
 '1309000H0',
 '1310011AA',
 '1310020D0',
 '1310020J0',
 '1310020Y0',
 '1310020Z0',
 '131003000',
 '1310030L0',
 '131005000',
 '1310050H0',
 '1310050J0',
 '1310050K0',
 '131101000',
 '1311010A0',
 '1311010I0',
 '1311020G0',
 '1311040T0',
 '1311050E0',
 '1311050U0',
 '1311060I0',
 '1311070S0',
 '1312000G0',
 '131500000',
 '1315000G0',
 '140400050',
 '1404000AF',
 '1404000AH',
 '1404000AI',
 '1404000AL',
 '1404000AQ',
 '1404000E0',
 '1404000N0',
 '1404000U0',
 '1404000W0',
 '1404000X0',
 '1501030D0',
 '1501042E0',
 '1501043A0',
 '1501043F0',
 '1502010C0',
 '1502010P0',
 '190203000',
 '1902070A0',
 '1902070E0',
 '190400000',
 '190601000',
 '190900000',
 '191300000',
 '1914010A0',
 '191402000',
 '200100001',
 '200100002',
 '200201001',
 '200202002',
 '200202004',
 '200202005',
 '200202006',
 '200302002',
 '200304003',
 '200307000',
 '200309003',
 '200312001',
 '200315000',
 '200321000',
 '200321001',
 '200322000',
 '200324000',
 '200325000',
 '200329000',
 '200402001',
 '200402003',
 '200403003',
 '200403004',
 '200501001',
 '200502002',
 '200502003',
 '200502005',
 '200503003',
 '200503004',
 '200700001',
 '200800001',
 '200900001',
 '200900003',
 '200900006',
 '200900007',
 '200900011',
 '200900012',
 '201000001',
 '201000002',
 '201000003',
 '201100003',
 '201500000',
 '201700001',
 '202000003',
 '210101001',
 '210102201',
 '210108001',
 '210112003',
 '210112004',
 '210113002',
 '210115001',
 '210115004',
 '210120001',
 '210124001',
 '210200001',
 '210200004',
 '210200006',
 '210300001',
 '210300003',
 '210300004',
 '210300007',
 '210400004',
 '210601001',
 '210601002',
 '210602001',
 '210602002',
 '210602003',
 '210701009',
 '210703001',
 '210704201',
 '210705102',
 '210705201',
 '210705301',
 '211800000',
 '212500001',
 '212700005',
 '212700012',
 '212700013',
 '212700014',
 '212700016',
 '212700017',
 '212700018',
 '212700019',
 '212700020',
 '212700021',
 '213000002',
 '213000005',
 '213000006',
 '213000008',
 '213000009',
 '213300001',
 '213500001',
 '213600001',
 '213700001',
 '213900001',
 '214000001',
 '214200001',
 '214300001',
 '214601000',
 '214701000',
 '220210005',
 '220238305',
 '220509505',
 '220517505',
 '220520805',
 '220524005',
 '220526500',
 '220529505',
 '220548805',
 '220550505',
 '220560505',
 '220561505',
 '221504515',
 '221510015',
 '223005030',
 '223009030',
 '223020830',
 '223024030',
 '223029530',
 '224003040',
 '224010040',
 '224012540',
 '224023540',
 '224024040',
 '224029540',
 '224034040',
 '224041040',
 '224048040',
 '225001050',
 '225007550',
 '225017550',
 '225024050',
 '225029550',
 '225048850',
 '225060550',
 '225061550',
 '226004560',
 '226007560',
 '226017560',
 '226024060',
 '226029560',
 '226034560',
 '226041060',
 '226048060',
 '226048860',
 '226053060',
 '226056060',
 '226061560',
 '227024070',
 '227029570',
 '227048870',
 '228001080',
 '228007580',
 '228009580',
 '228023280',
 '228024080',
 '228029580',
 '228034080',
 '228039580',
 '228050580',
 '228061580',
 '228062080',
 '228534980',
 '229001090',
 '229006090',
 '229007590',
 '229021990',
 '229024090',
 '229029590',
 '229034090',
 '229034091',
 '229038990',
 '230506005',
 '230507005',
 '230510605',
 '230524005',
 '230533505',
 '230534505',
 '230559005',
 '230565005',
 '231001010',
 '231530615',
 '231533515',
 '231539315',
 '231559015',
 '232001020',
 '232007020',
 '232009020',
 '232010020',
 '232041020',
 '232048020',
 '232502625',
 '232506025',
 '232510525',
 '232510825',
 '232524025',
 '232533725',
 '232559525',
 '233001030',
 '233002631',
 '233004530',
 '233007030',
 '233010230',
 '233010231',
 '233010232',
 '233010530',
 '233010830',
 '233010831',
 '233024030',
 '233032430',
 '233034530',
 '233041030',
 '233041530',
 '233048030',
 '233056030',
 '233059030',
 '233059510',
 '233059511',
 '233501035',
 '233504535',
 '233504536',
 '233504537',
 '233510035',
 '233510036',
 '233510635',
 '233533535',
 '233533536',
 '233534535',
 '233541035',
 '233541036',
 '233541038',
 '233556035',
 '233556036',
 '233556037',
 '233559035',
 '234043040',
 '234506045',
 '234507045',
 '234510645',
 '234514545',
 '234522545',
 '234530645',
 '234534545',
 '234544045',
 '234559045',
 '234560045',
 '234604546',
 '234606046',
 '234610646',
 '234633546',
 '234633746',
 '234634546',
 '234648046',
 '234665046',
 '235010050',
 '235011050',
 '235033650',
 '235033750',
 '235512556',
 '235524055',
 '236001063',
 '236004561',
 '236007060',
 '236007061',
 '236010061',
 '236012562',
 '236024060',
 '236030561',
 '236033560',
 '236033561',
 '236034560',
 '236041060',
 '236041061',
 '236041063',
 '236041065',
 '236048060',
 '236048061',
 '236048062',
 '236056060',
 '236056061',
 '236056063',
 '236059060',
 '237001070',
 '237002770',
 '237004570',
 '237037570',
 '237056570',
 '237066070',
 '237510075',
 '237533775',
 '237541075',
 '237548075',
 '238006080',
 '238010680',
 '238020880',
 '238022280',
 '238029580',
 '238033580',
 '238047080',
 '238065580',
 '238506085',
 '238524085',
 '238533585',
 '238533785',
 '238541585',
 '238548085',
 '238559085',
 '239001090',
 '239004590',
 '239010090',
 '239033590',
 '239034590',
 '239041090',
 '239048090',
 '239056090',
 '239059090',
 '239201092',
 '239241092',
 '239259092',
 '239404594',
 '239404595',
 '239407098',
 '239410095',
 '239410097',
 '239410098',
 '239433500',
 '239441094',
 '239448098',
 '239448099',
 '239448100',
 '239456094',
 '239456095',
 '239459094',
 '239459095',
 '239601096',
 '239601098',
 '239604596',
 '239610097',
 '239630597',
 '239632496',
 '239633596',
 '239648096',
 '239659096'}

In [143]:
rare_codes = set(rates[rates < 0.1*p].index)

In [144]:
scripts['rare'] = scripts['bnf_code'].isin(rare_codes)

In [145]:
scripts.head()

,practice,bnf_code,bnf_name,items,nic,act_cost,quantity,opioid,rare
0,N85639,0106020C0,Bisacodyl_Tab E/C 5mg,1,0.39,0.47,12,False,False
1,N85639,0106040M0,Movicol Plain_Paed Pdr Sach 6.9g,1,4.38,4.07,30,False,False
2,N85639,0301011R0,Salbutamol_Inha 100mcg (200 D) CFF,1,1.50,1.40,1,False,False
3,N85639,0304010G0,Chlorphenamine Mal_Oral Soln 2mg/5ml,1,2.62,2.44,150,False,False
4,N85639,0401020K0,Diazepam_Tab 2mg,1,0.16,0.26,6,False,False

Now for each practice, calculate the proportion of costs that originate from prescription of rare treatments (i.e. rare `'bnf_code'`). Use the `'act_cost'` field for this calculation.

In [146]:
rare_cost_prop = (scripts[scripts['rare']].groupby('practice')['act_cost'].sum()\
/scripts.groupby('practice')['act_cost'].sum()).fillna(0)
#\ means code continues in next line

In [147]:
rare_cost_prop

practice
A81005    0.012017
A81007    0.008381
A81011    0.005116
A81012    0.013747
A81017    0.007359
            ...
Y05570    0.000000
Y05583    0.000000
Y05597    0.000000
Y05660    0.000323
Y05670    0.000000
Name: act_cost, Length: 856, dtype: float64

Now we will calculate a z-score for each practice based on this proportion.
First take the difference of `rare_cost_prop` and the proportion of costs originating from rare treatments across all practices.

In [148]:
relative_rare_cost_prop = rare_cost_prop - \
scripts[scripts['rare']]['act_cost'].sum()/scripts['act_cost'].sum()

Now we will estimate the standard errors (i.e. the denominator of the z-score) by simply taking the standard deviation of this difference.

In [149]:
standard_errors = relative_rare_cost_prop.std()
#finding the standard deviation of relative_rare_cost_prop

In [150]:
standard_errors

0.06050888706745139

In [151]:
relative_rare_cost_prop/standard_errors #z-score

practice
A81005   -0.065216
A81007   -0.125308
A81011   -0.179263
A81012   -0.036615
A81017   -0.142190
            ...
Y05570   -0.263811
Y05583   -0.263811
Y05597   -0.263811
Y05660   -0.258473
Y05670   -0.263811
Name: act_cost, Length: 856, dtype: float64

Finally compute the z-scores. Return the practices with the top 100 z-scores in the form `(practice_code, practice_name, z-score)`. Note that some practice codes will correspond with multiple names. In this case, use the first match when sorting names alphabetically.

In [152]:
rare_scores = (relative_rare_cost_prop/standard_errors).reset_index().rename(columns={'act_cost':'z-score'}) 
#Z-scores

In [153]:
rare_scores

    practice   z-score
0     A81005 -0.065216
1     A81007 -0.125308
2     A81011 -0.179263
3     A81012 -0.036615
4     A81017 -0.142190
..       ...       ...
851   Y05570 -0.263811
852   Y05583 -0.263811
853   Y05597 -0.263811
854   Y05660 -0.258473
855   Y05670 -0.263811

[856 rows x 2 columns]

In [154]:
type(rare_scores)

pandas.core.frame.DataFrame

In [155]:
unique_practices_by_name
#dataframe already created in question 4

         code                                    name
0      A81001                     THE DENSHAM SURGERY
1      A81002              QUEENS PARK MEDICAL CENTRE
2      A81003               VICTORIA MEDICAL PRACTICE
3      A81004                 BLUEBELL MEDICAL CENTRE
4      A81005                      SPRINGWOOD SURGERY
...       ...                                     ...
10838  Y05758                     VC SKELMERSDALE UCC
10839  Y05762                  WEST MERTON ACCESS HUB
10840  Y05763           ELY LOCAL URGENT CARE SERVICE
10841  Y05764                     MINOR INJURIES UNIT
10842  Y05771  URGENT CARE CENTRE NORTHWICK PARK HOSP

[10843 rows x 2 columns]

In [156]:
rare_scores.merge(unique_practices_by_name,how='left',left_on='practice',right_on='code')

    practice   z-score    code                                 name
0     A81005 -0.065216  A81005                   SPRINGWOOD SURGERY
1     A81007 -0.125308  A81007                    BANKHOUSE SURGERY
2     A81011 -0.179263  A81011                    CHADWICK PRACTICE
3     A81012 -0.036615  A81012            WESTBOURNE MEDICAL CENTRE
4     A81017 -0.142190  A81017                  WOODBRIDGE PRACTICE
..       ...       ...     ...                                  ...
851   Y05570 -0.263811  Y05570         OLDHAM 7 DAY ACCESS HUB3 OOH
852   Y05583 -0.263811  Y05583                   CYPS - ACORN HOUSE
853   Y05597 -0.263811  Y05597  WORKING AGE ADULTS - ST OWEN STREET
854   Y05660 -0.258473  Y05660       BRENT GP ACCESS WALK-IN CENTRE
855   Y05670 -0.263811  Y05670     SUNDERLAND NORTH EXTENDED ACCESS

[856 rows x 4 columns]

In [157]:
dff=rare_scores.merge(unique_practices_by_name,how='left',left_on='practice',right_on='code')[['code','name','z-score']]

In [158]:
dff

       code                                 name   z-score
0    A81005                   SPRINGWOOD SURGERY -0.065216
1    A81007                    BANKHOUSE SURGERY -0.125308
2    A81011                    CHADWICK PRACTICE -0.179263
3    A81012            WESTBOURNE MEDICAL CENTRE -0.036615
4    A81017                  WOODBRIDGE PRACTICE -0.142190
..      ...                                  ...       ...
851  Y05570         OLDHAM 7 DAY ACCESS HUB3 OOH -0.263811
852  Y05583                   CYPS - ACORN HOUSE -0.263811
853  Y05597  WORKING AGE ADULTS - ST OWEN STREET -0.263811
854  Y05660       BRENT GP ACCESS WALK-IN CENTRE -0.258473
855  Y05670     SUNDERLAND NORTH EXTENDED ACCESS -0.263811

[856 rows x 3 columns]

In [159]:
dff.sort_values('z-score',ascending=False)[:100]

       code                               name    z-score
765  Y03472           CONSULTANT DIABETES TEAM  16.262687
831  Y05320     DMC COMMUNITY DERMATOLOGY RBWF  15.128648
793  Y04404  OUTPATIENTS JUBILEE HEALTH CENTRE   7.542139
766  Y03484   DMC COMMUNITY DERMATOLOGY CLINIC   7.287222
794  Y04424                     DMC HEALTHCARE   6.838614
..      ...                                ...        ...
738  Y02671     THE PRACTICE HEART OF HOUNSLOW   0.208809
242  F84631                       DR PI ABIOLA   0.205391
61   B81012                        DR AP KUMAR   0.203691
128  C83613              CAISTOR HEALTH CENTRE   0.203500
448  M91614                    STROUD PRACTICE   0.200505

[100 rows x 3 columns]

In [160]:
#rare_scripts = [("Y03472", "CONSULTANT DIABETES TEAM", 16.2626871247)] * 100

In [161]:
rare_scripts = [item[1:] for item in dff.sort_values('z-score',ascending=False)[:100].itertuples()]

In [162]:
rare_scripts

[('Y03472', 'CONSULTANT DIABETES TEAM', 16.262687124655073),
 ('Y05320', 'DMC COMMUNITY DERMATOLOGY RBWF', 15.128648195416869),
 ('Y04404', 'OUTPATIENTS JUBILEE HEALTH CENTRE', 7.54213935610462),
 ('Y03484', 'DMC COMMUNITY DERMATOLOGY CLINIC', 7.287222200297828),
 ('Y04424', 'DMC HEALTHCARE', 6.838614181432866),
 ('Y00631', 'BINGLEY DERMATOLOGY CLINIC', 5.75599754983774),
 ('A89038', 'BARMSTON MEDICAL CENTRE', 5.664940368539935),
 ('Y01696', 'BASSETLAW HOSPICE OF THE GOOD SHEPHERD', 4.290685171474921),
 ('Y03699', 'OLDHAM DERMATOLOGY SERVICE', 4.103743999157244),
 ('Y02045', 'VERNOVA HEALTHCARE CIC', 3.1807154704143983),
 ('Y02823', 'DMC VICARAGE LANE', 3.054121649498702),
 ('Y00997', 'COMMUNITY DERMATOLOGY SERVICE', 3.018128359535277),
 ('Y05019', 'OLDHAM TOTAL SKIN SERVICE', 2.7247515958989283),
 ('Y01003', 'BURY OOH', 2.350436347139858),
 ('Y05431', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 2.0371585432333865),
 ('Y03557', 'IPU 10-17 RECOVERY COVENTRY', 2.0304495001187792),
 ('Y05419', 'WEEKEND WORKING EASINGTON NORTH', 2.0029603055317033),
 ('Y05434', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.617815561802807),
 ('L84042', 'LONDON MEDICAL PRACTICE', 1.6040122379818667),
 ('Y04871', 'LEARNING ASSESSMENT & NEUROCARE BURY', 1.4408185020947357),
 ('Y05432', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.3052021753375485),
 ('F86057', 'THE WILLOWS PRACTICE', 1.280956281894272),
 ('L81673', 'BCH DERMATOLOGY SERVICE', 1.2779474429274984),
 ('Y04089', 'VIRGIN CARE (MIDDLESBROUGH)', 1.205585821536491),
 ('Y03762', 'BASSETLAW HEALTH PARTNERSHIP', 1.1547690310997736),
 ('Y05430', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.122760467986764),
 ('B85030', 'SCRIVINGS CLECKHEATON HLTH CTR', 1.103502377336562),
 ('P81736', 'WHITEFIELD HEALTHCARE', 1.0939581886026775),
 ('Y00570', 'GP LED DERMATOLOGY SERVICE', 1.051561915279194),
 ('Y04606', 'LANCASTER HOUSE CONTINENCE', 1.0328515953934714),
 ('P81712', 'DARWEN HEALTH CENTRE', 1.0286324480322657),
 ('Y05433', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 1.027801098310148),
 ('Y02943', 'NEUROLOGY LONG TERM CONDITIONS', 0.9576943719522105),
 ('P84051', 'EASTLANDS MEDICAL CENTRE', 0.9070372260702894),
 ('Y02203', 'DURHAM DALES EAST DERMATOLOGY', 0.8830665514715633),
 ('G82704', 'THE CHURCH VIEW PRACTICE', 0.8688187586905597),
 ('F81070', 'GRAFTON SURGERY', 0.8466362126602007),
 ('Y05435', 'NOTTS APPLIANCE MANAGEMENT SERVICE', 0.8245199350473523),
 ('P82625', 'CHARLOTTE STREET SURGERY', 0.7738455888380996),
 ('P82640', 'AL FAL MEDICAL GROUP', 0.7188956515487629),
 ('F84706', 'DR SKS SWEDAN', 0.7187925567143413),
 ('Y01168', 'COMMUNITY GYNAECOLOGY SERVICE', 0.680294754937742),
 ('N81080', 'NORTHGATE MEDICAL CENTRE', 0.6661638079014608),
 ('A87022', 'NORTHUMBERLAND PARK MEDICAL GROUP', 0.6387318815059378),
 ('B83058', 'THE AVICENNA MEDICAL PRACTICE', 0.5975595360581426),
 ('M85766', 'BALSALL HEATH HEALTH CENTRE (S)', 0.5631450010961307),
 ('G81658', 'THE STATION PRACTICE', 0.5331888751077345),
 ('M85715', 'SOHO ROAD PRIMARY CARE CENTRE', 0.5292269288022778),
 ('E85659', 'DR RK KUKAR  PARKVIEW CTR FOR H&W', 0.5224575320213929),
 ('M85716', "DR KHUROO'S PRACTICE", 0.5057276127409458),
 ('B83067', 'THE SPRINGFIELD SURGERY (BINGLEY)', 0.501482611056885),
 ('B84011', 'CHURCH LANE SURGERY', 0.4971525440866812),
 ('B83032', 'BRADFORD MOOR PRACTICE', 0.4846018519341162),
 ('Y00469', "DR MA SIMS' PRACTICE", 0.4807898234276762),
 ('H81034', 'MADEIRA MEDICAL', 0.4734461208205337),
 ('A83071', 'THE NEW SEAHAM MEDICAL GROUP', 0.449331293126233),
 ('P91633', 'GROVE MEDICAL PRACTICE', 0.41490953303333816),
 ('P84032', 'DR MOKASHI', 0.41412117824419364),
 ('F84086', 'DR DRIVER & PARTNERS', 0.41010853569042116),
 ('C83041', 'THE WOODLAND MEDICAL PRACTICE', 0.40138982620908986),
 ('G82162', 'RAINHAM HEALTHY LIVING CENTRE', 0.393922979076173),
 ('A83051', 'MARLBOROUGH SURGERY', 0.3778275531156093),
 ('C84714', 'SUNRISE MEDICAL PRACTICE (GHATTAORA)', 0.36171473108349395),
 ('B82016', 'EAST PARADE SURGERY', 0.3557702463337187),
 ('C84691', 'HIGHGREEN PRACTICE (KHAN)', 0.3433615333473626),
 ('L82001', 'LANDER MEDICAL PRACTICE', 0.33235665421941707),
 ('G84027', 'ELM HOUSE SURGERY', 0.32992048438337207),
 ('Y02957', 'LEWISHAM GP LED HEALTH CENTRE', 0.32435502195888544),
 ('G85095', 'MANOR PLACE SURGERY', 0.31837462196154365),
 ('E82656', 'CASSIO SURGERY - E82656', 0.30990494051873824),
 ('M91017', 'NORTHGATE MEDICAL CENTRE', 0.30899661675601364),
 ('L84008', "ST.GEORGE'S SURGERY", 0.3030552835025272),
 ('P81099', 'DR THM MACKENZIE & PARTNERS', 0.2999109640678622),
 ('E85018', "DR SOOD'S PRACTICE", 0.28911226062072876),
 ('Y04951', 'ARDEN HEALTHCARE CENTRE', 0.2887489271620815),
 ('N82051', 'BREEZE HILL - SSP HEALTH LIMITED', 0.28046854394239895),
 ('H81097', 'RIVER WEY MEDICAL PRACTICE', 0.2791932466218151),
 ('C82667', 'THE CHARNWOOD PRACTICE', 0.27023096949600767),
 ('C87622', 'GATEWAY PRIMARY CARE', 0.2664585596184689),
 ('E85723', 'NORTHOLT FAMILY PRACTICE', 0.26528020519467377),
 ('C84013', 'BRIDGEGATE AND TALL TREES PARTNERSHIP', 0.26366935264953073),
 ('E85126', 'GREEN PRACTICE', 0.26221153146662574),
 ('P92024', 'THE CHANDLER SURGERY', 0.26051575498627844),
 ('Y01929', 'TELDOC', 0.25690238903585116),
 ('K82078', 'DR ALLAN AND PARTNERS', 0.2533573488637121),
 ('M85068', 'THE VESEY PRACTICE', 0.25158414215632147),
 ('G85034', 'NEXUS HEALTH GROUP', 0.2478114526939599),
 ('P88023', 'HEALD GREEN HEALTH CENTRE 2', 0.24216851539060344),
 ('M83629', 'DRAYTON ROAD SURGERY', 0.2336160725696232),
 ('M83063', 'NORTON CANES HEALTH CENTRE', 0.23290147960328128),
 ('H81615', 'FARNHAM DENE MEDICAL PRACTICE', 0.23242313968072845),
 ('D81024', 'THOMAS WALKER', 0.22415411809062796),
 ('K83051', 'WEAVERS MEDICAL', 0.22201042583580333),
 ('G85134', 'THE LISTER PRIMARY CARE CENTRE', 0.21810202517578295),
 ('Y00278', 'DARLASTON HEALTH CENTRE-KHAN', 0.21228353307860784),
 ('Y02671', 'THE PRACTICE HEART OF HOUNSLOW', 0.20880880182432582),
 ('F84631', 'DR PI ABIOLA', 0.20539081662007141),
 ('B81012', 'DR AP KUMAR', 0.20369059525865613),
 ('C83613', 'CAISTOR HEALTH CENTRE', 0.20350023874284506),
 ('M91614', 'STROUD PRACTICE', 0.20050528609272353)]

In [166]:
grader.score.dw__rare_scripts(rare_scripts)

==================
Your score: 1.000
==================

*Copyright &copy; 2021 WorldQuant University. This content is licensed solely for personal use. Redistribution or publication of this material is strictly prohibited.*